# YouTube Comment Collection — FUZZ CHANNEL

**Project 2 | High Performance Data Processing (SECP3133)**  
**Data Source:** YouTube comments from smartphone review videos on FUZZ CHANNEL (Malaysian tech review channel)

---

This notebook collects raw YouTube comments from smartphone review videos published on **FUZZ CHANNEL**. The collected comments serve as the primary text corpus for downstream sentiment analysis.

### Pipeline overview

Youtube Data API v3 -> Channel ID -> Filter: Smartphone Review Videos -> Fetch Comments (Paginated) -> Save into **raw_data.csv**

### Collected fields
| Field | Description |
|---|---|
| `video_id` | YouTube video identifier |
| `video_title` | Title of the review video |
| `video_published_at` | Upload date of the video |
| `comment_id` | Unique comment identifier |
| `author` | Display name of the commenter |
| `comment_text` | Raw comment text |
| `like_count` | Number of likes on the comment |
| `reply_count` | Number of replies to the comment thread |
| `published_at` | Timestamp the comment was posted |
| `updated_at` | Timestamp of last edit (if any) |

## 1. Setup and Imports

We rely on the following libraries:

- **`google-api-python-client`** — official Google client library wrapping the YouTube Data API v3.
- **`pandas`** — tabular data manipulation and CSV export.
- **`tqdm`** — lightweight progress bars for long-running loops.
- **`time` / `datetime`** — rate-limit back-off and timestamping.

> Install any missing package with: `pip install google-api-python-client pandas tqdm`

In [11]:
import os
import time
import json
from datetime import datetime

import pandas as pd
from tqdm import tqdm
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

print("Libraries loaded successfully.")

Libraries loaded successfully.

## 2. Configuration

Set your YouTube Data API v3 key and the collection parameters below.

| Parameter | Purpose |
|---|---|
| `API_KEY` | Authenticates requests to the YouTube Data API. |
| `CHANNEL_QUERY` | Search term used to locate FUZZ CHANNEL. |
| `PHONE_KEYWORDS` | Title keywords that identify smartphone review videos. |
| `MAX_COMMENTS_PER_VIDEO` | Upper bound on comments fetched per video (`None` = all). |
| `REQUEST_DELAY` | Seconds to wait between API calls to avoid quota bursts. |
| `OUTPUT_DIR` | Directory where the raw CSV will be written. |

> **Quota note:** The YouTube Data API v3 grants **10,000 units per day** on a free key.  
> Each `commentThreads.list` call costs **1 unit** and returns up to 100 comments.  
> With 10,000 units you can pull roughly 1,000,000 comments — more than enough for this project.

In [4]:
# ── Authentication ─────────────────────────────────────────────────────────────
API_KEY = "AIzaSyBRC-kqbV7LDOKKh6QqVc32hNidK46V_CQ"  

# ── Channel targeting ──────────────────────────────────────────────────────────
CHANNEL_QUERY = "FUZZ CHANNEL"  # Search term to locate the channel

# Keywords that identify smartphone / phone review videos (case-insensitive).
# A video is included if its title contains AT LEAST ONE of these terms.
PHONE_KEYWORDS = [
    "review", "unboxing", "hands on", "hands-on",
    "phone", "smartphone", "flagship",
    "samsung", "xiaomi", "realme", "oppo", "vivo",
    "iphone", "apple", "pixel", "huawei", "nothing",
    "redmi", "oneplus", "motorola", "infinix", "tecno",
]

# ── Collection limits ──────────────────────────────────────────────────────────
MAX_COMMENTS_PER_VIDEO = None   # None = collect every available comment
MAX_TOTAL_COMMENTS     = 3000   # stop collection once this total is reached

REQUEST_DELAY          = 0.3    # seconds between API calls

# ── Output ─────────────────────────────────────────────────────────────────────
OUTPUT_DIR  = r"c:\UTM things\Year 3\SEM 2\HDPD\Project 2\data\raw_data"
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "youtube_comments_raw.csv")

os.makedirs(OUTPUT_DIR, exist_ok=True)
print(f"Output directory: {os.path.abspath(OUTPUT_DIR)}")

Output directory: c:\UTM things\Year 3\SEM 2\HDPD\Project 2\data\raw_data

## 3. Build the API Client

`googleapiclient.discovery.build` constructs a service object for the YouTube Data API v3.  
All subsequent calls go through this single client instance.

In [5]:
youtube = build("youtube", "v3", developerKey=API_KEY)
print("YouTube API client ready.")

YouTube API client ready.

## 4. Locate FUZZ CHANNEL

We use the **`search.list`** endpoint with `type=channel` to find FUZZ CHANNEL and retrieve its unique **channel ID**.  
The channel ID is then used to access the channel's upload playlist.

The **`channels.list`** endpoint returns a `contentDetails.relatedPlaylists.uploads` field — a special playlist that contains every video the channel has ever uploaded, in reverse-chronological order.

In [6]:
def get_channel_id(youtube_client, query):
    """
    Search for a YouTube channel by name and return (channel_id, channel_title).
    Raises ValueError if no channel is found.
    """
    response = youtube_client.search().list(
        q=query,
        type="channel",
        part="snippet",
        maxResults=5,
    ).execute()

    items = response.get("items", [])
    if not items:
        raise ValueError(f"No channel found for query: '{query}'")

    # Print all candidates so we can verify we picked the right one
    print("Candidate channels found:")
    for i, item in enumerate(items):
        cid   = item["snippet"]["channelId"]
        title = item["snippet"]["title"]
        print(f"  [{i}] {title}  (id: {cid})")

    channel_id    = items[0]["snippet"]["channelId"]
    channel_title = items[0]["snippet"]["title"]
    return channel_id, channel_title


def get_uploads_playlist_id(youtube_client, channel_id):
    """
    Return the uploads playlist ID for a given channel.
    This playlist contains all videos uploaded to the channel.
    """
    response = youtube_client.channels().list(
        id=channel_id,
        part="contentDetails",
    ).execute()

    return response["items"][0]["contentDetails"]["relatedPlaylists"]["uploads"]


# ── Execute ────────────────────────────────────────────────────────────────────
CHANNEL_ID, CHANNEL_TITLE = get_channel_id(youtube, CHANNEL_QUERY)
UPLOADS_PLAYLIST_ID       = get_uploads_playlist_id(youtube, CHANNEL_ID)

print(f"\nSelected channel : {CHANNEL_TITLE}")
print(f"Channel ID       : {CHANNEL_ID}")
print(f"Uploads playlist : {UPLOADS_PLAYLIST_ID}")

Candidate channels found:
  [0] FUZZ CHANNEL  (id: UCNgBXwadunmKRt0TksSFaqw)
  [1] Fuzz  (id: UCk_YaS7EjbnUe6r_1colvlA)
  [2] More Fuzz  (id: UC_I3PBtw880M77iQWKUY1Fg)
  [3] MrFuzzy  (id: UCxy7M1_T8OSGRrWaJNsMfrQ)
  [4] fuzz  (id: UCGacX4lqGSqYXZjnXrDPTOg)

Selected channel : FUZZ CHANNEL
Channel ID       : UCNgBXwadunmKRt0TksSFaqw
Uploads playlist : UUNgBXwadunmKRt0TksSFaqw

## 5. Fetch All Uploaded Videos

The **`playlistItems.list`** endpoint is the most efficient way to enumerate a channel's videos.  
It returns up to **50 items per page**, so we paginate using `nextPageToken` until all pages are exhausted.

For each video we capture:
- `video_id` — needed to fetch its comments
- `video_title` — used to filter for smartphone-related content
- `video_published_at` — for time-series analysis later

In [7]:
def fetch_all_videos(youtube_client, playlist_id):
    """
    Paginate through a playlist and return a list of video metadata dicts.
    Each dict contains: video_id, video_title, video_published_at.
    """
    videos     = []
    page_token = None

    print("Fetching video list from uploads playlist ...")
    while True:
        request_kwargs = dict(
            playlistId=playlist_id,
            part="snippet,contentDetails",
            maxResults=50,
        )
        if page_token:
            request_kwargs["pageToken"] = page_token

        response   = youtube_client.playlistItems().list(**request_kwargs).execute()
        page_items = response.get("items", [])

        for item in page_items:
            snippet = item["snippet"]
            videos.append({
                "video_id"           : snippet["resourceId"]["videoId"],
                "video_title"        : snippet.get("title", ""),
                "video_published_at" : snippet.get("publishedAt", ""),
            })

        page_token = response.get("nextPageToken")
        if not page_token:
            break

        time.sleep(REQUEST_DELAY)

    print(f"Total videos found: {len(videos)}")
    return videos


all_videos = fetch_all_videos(youtube, UPLOADS_PLAYLIST_ID)

Fetching video list from uploads playlist ...
Total videos found: 1246

## 6. Filter for Smartphone Review Videos

FUZZ CHANNEL covers a variety of tech content. We narrow the scope to **smartphone review videos** by checking whether each video title contains at least one of the keywords defined in `PHONE_KEYWORDS`.

This keeps the dataset focused and relevant for sentiment analysis around phone purchases and opinions.

In [8]:
def is_phone_video(title, keywords):
    """Return True if the title contains at least one phone-related keyword."""
    title_lower = title.lower()
    return any(kw.lower() in title_lower for kw in keywords)


phone_videos = [
    v for v in all_videos
    if is_phone_video(v["video_title"], PHONE_KEYWORDS)
]

print(f"Total videos on channel  : {len(all_videos)}")
print(f"Smartphone review videos : {len(phone_videos)}")
print()
print("Sample of matched videos:")
for v in phone_videos[:10]:
    print(f"  [{v['video_published_at'][:10]}] {v['video_title']}")

Total videos on channel  : 1246
Smartphone review videos : 898

Sample of matched videos:
  [2026-06-11] Aku Beli iPhone 17 Pro Harga RM200! Tak Sangka…
  [2026-06-11] iPhone aku dah update iOS 27 😍
  [2026-06-09] Semua Ciri Baru iOS 27 Pengguna iPhone Wajib Tahu!
  [2026-05-30] 25 Fungsi Menarik iPhone Tak Ramai Tahu!
  [2026-05-28] Xiaomi 17T Pro Terlalu Bagus Untuk Harga Bawah RM3000!
  [2026-05-20] Benda Penting Pasal iOS 27 + iPhone Ultra! 🔥
  [2026-05-17] Sebab iPhone 17 paling laku sekarang 😱
  [2026-05-16] Fon Flagship Bawah RM2000 Paling Power! – POCO X8 Pro Max Malaysia 🔥
  [2026-05-11] iPhone 17 Review : Phone Paling Laris 2026!
  [2026-05-09] iPhone Ultra foldable pertama Apple dah confirmed?! 😱

## 7. Comment Collection — Helper Function

For each smartphone review video we call **`commentThreads.list`**, which returns top-level comment threads.

### Pagination
The endpoint returns a maximum of **100 comments per page**. We loop on `nextPageToken` until either:
- There are no more pages, or
- We have reached `MAX_COMMENTS_PER_VIDEO` (if set).

### Error handling
| HTTP error | Cause | Action |
|---|---|---|
| 403 `commentsDisabled` | Channel/video has comments turned off | Skip video, log warning |
| 403 `forbidden` | Video is private or age-restricted | Skip video, log warning |
| 404 | Video deleted after playlist was fetched | Skip video, log warning |
| 429 / 5xx | Quota exhausted or server error | Raise immediately |

In [9]:
def fetch_comments_for_video(youtube_client, video_id, max_comments=None):
    """
    Fetch all top-level comments for a single video.

    Returns a list of comment dicts.
    Returns an empty list if comments are disabled or the video is unavailable.
    """
    comments   = []
    page_token = None

    while True:
        try:
            request_kwargs = dict(
                videoId=video_id,
                part="snippet",
                maxResults=100,
                textFormat="plainText",
                order="relevance",
            )
            if page_token:
                request_kwargs["pageToken"] = page_token

            response = youtube_client.commentThreads().list(**request_kwargs).execute()

        except HttpError as e:
            error_reason = ""
            try:
                error_body   = json.loads(e.content)
                error_reason = error_body["error"]["errors"][0]["reason"]
            except Exception:
                pass

            if e.resp.status in (403, 404):
                # Comments disabled, private video, or age-restricted — skip gracefully
                print(f"    [SKIP] {video_id}: {error_reason or e.resp.status}")
                return []
            else:
                raise  # Re-raise unexpected errors (quota exhausted, server errors)

        for item in response.get("items", []):
            top = item["snippet"]["topLevelComment"]["snippet"]
            comments.append({
                "comment_id"   : item["snippet"]["topLevelComment"]["id"],
                "author"       : top.get("authorDisplayName", ""),
                "comment_text" : top.get("textDisplay", ""),
                "like_count"   : top.get("likeCount", 0),
                "reply_count"  : item["snippet"].get("totalReplyCount", 0),
                "published_at" : top.get("publishedAt", ""),
                "updated_at"   : top.get("updatedAt", ""),
            })

        # Check early-stop condition
        if max_comments and len(comments) >= max_comments:
            comments = comments[:max_comments]
            break

        page_token = response.get("nextPageToken")
        if not page_token:
            break

        time.sleep(REQUEST_DELAY)

    return comments


print("Comment fetcher defined.")

Comment fetcher defined.

## 8. Run the Collection Loop

Iterate over every smartphone review video and accumulate comments into a single flat list.  
A `tqdm` progress bar tracks per-video progress, and running totals are printed after each video.

In [13]:
all_records  = [] # Final flat list of (video metadata + comment) dicts
skipped      = [] # Videos with no collectible comments

print(f"Starting collection for {len(phone_videos)} videos (cap: {MAX_TOTAL_COMMENTS:,} total comments) ...\n")

for video in tqdm(phone_videos, desc="Videos", unit="video"):
    if len(all_records) >= MAX_TOTAL_COMMENTS:
        print(f"\nReached {MAX_TOTAL_COMMENTS:,} comment cap — stopping early.")
        break

    vid_id    = video["video_id"]
    vid_title = video["video_title"]

    # Only fetch as many comments as we still need
    remaining = MAX_TOTAL_COMMENTS - len(all_records)

    comments = fetch_comments_for_video(
        youtube,
        video_id=vid_id,
        max_comments=remaining,
    )

    if not comments:
        skipped.append(vid_id)
        continue

    for comment in comments:
        all_records.append({
            "video_id"           : vid_id,
            "video_title"        : vid_title,
            "video_published_at" : video["video_published_at"],
            **comment,
        })

    print(
        f"  [OK] {vid_title[:65]!r}  ->  {len(comments):,} comments  "
        f"(total so far: {len(all_records):,})"
    )
    time.sleep(REQUEST_DELAY)

print(f"\nCollection complete.")
print(f"  Total comments collected : {len(all_records):,}")
print(f"  Videos skipped           : {len(skipped)}")

Starting collection for 898 videos (cap: 3,000 total comments) ...

  [OK] 'Aku Beli iPhone 17 Pro Harga RM200! Tak Sangka…'  ->  6 comments  (total so far: 6)

  [OK] 'Semua Ciri Baru iOS 27 Pengguna iPhone Wajib Tahu!'  ->  19 comments  (total so far: 25)

  [OK] '25 Fungsi Menarik iPhone Tak Ramai Tahu!'  ->  32 comments  (total so far: 57)

  [OK] 'Xiaomi 17T Pro Terlalu Bagus Untuk Harga Bawah RM3000!'  ->  34 comments  (total so far: 91)

  [OK] 'Benda Penting Pasal iOS 27 + iPhone Ultra! 🔥'  ->  24 comments  (total so far: 115)

  [OK] 'Sebab iPhone 17 paling laku sekarang 😱'  ->  47 comments  (total so far: 162)

  [OK] 'Fon Flagship Bawah RM2000 Paling Power! – POCO X8 Pro Max Malaysi'  ->  52 comments  (total so far: 214)

  [OK] 'iPhone 17 Review : Phone Paling Laris 2026!'  ->  68 comments  (total so far: 282)

  [OK] 'iPhone Ultra foldable pertama Apple dah confirmed?! 😱'  ->  20 comments  (total so far: 302)

  [OK] 'iPhone SEDAP Guna Tahun 2026 ~ 2027 Makin Murah!'  ->  91 comments  (total so far: 393)

  [OK] 'iPhone Ultra Dah Confirmed?! – Foldable Pertama Apple Harga RM10,'  ->  20 comments  (total so far: 413)

  [OK] 'Lepas ni bateri phone boleh tukar sendiri? 🤔'  ->  170 comments  (total so far: 583)

  [OK] 'OPPO Find X9 Ultra : Sebuah Kamera Dalam Badan Smartphone'  ->  16 comments  (total so far: 599)

  [OK] 'VIVO X300 Ultra Pertama Kali Masuk Malaysia!'  ->  22 comments  (total so far: 621)

  [OK] '10 Smartphone Dengan Bateri Besar Tak Masuk Akal! 🔥'  ->  37 comments  (total so far: 658)

  [OK] 'OPPO Find X9 Ultra Terlalu Bagus Sampai iPhone 17 Pro Kena Tingga'  ->  27 comments  (total so far: 685)

  [OK] 'HONOR 600 Pro Tiru iPhone 17 Pro? – Banyak Benda Ramai Tak Tahu!'  ->  28 comments  (total so far: 713)

  [OK] 'Sebab Tim Cook Tinggalkan Apple! – Perubahan Besar Akan Berlaku?!'  ->  66 comments  (total so far: 779)

  [OK] 'HONOR 600 Pro Makin Mengganas Dengan Flagship Mampu Milik!'  ->  39 comments  (total so far: 818)

  [OK] 'OPPO Find X9 Ultra : Pencabar Hebat Xiaomi & VIVO Ultra di Malays'  ->  35 comments  (total so far: 853)

  [OK] 'vivo V70 FE : Fon Bajet RM1500 Boleh Dapat Kamera 200MP!'  ->  18 comments  (total so far: 871)

  [OK] 'iPhone 600 Pro atau HONOR 17 Pro? 🤔'  ->  9 comments  (total so far: 880)

  [OK] 'Unboxing iPhone 18 Pro Pertama di Planet Bumi! 🔥'  ->  119 comments  (total so far: 999)

  [OK] 'Samsung Galaxy A37 vs A57 : Patut Beli Mana Satu?'  ->  58 comments  (total so far: 1,057)

  [OK] 'iPhone 17 Pro Max naik rocket sampai angkas lepas! 😱'  ->  32 comments  (total so far: 1,089)

  [OK] 'Kamera realme 16 Pro+ 5G Kali Ni Memang ANOTHER LEVEL!'  ->  24 comments  (total so far: 1,113)

  [OK] 'Samsung dah boleh AirDrop / Quick Share dengan iPhone!'  ->  3 comments  (total so far: 1,116)

  [OK] 'Nothing Phone 4a Pro Akhirnya Berubah!'  ->  59 comments  (total so far: 1,175)

  [OK] 'Update iPhone korang sekarang dari kena hack!'  ->  33 comments  (total so far: 1,208)

  [OK] 'iPhone Dah Tak Selamat? – Update Penting Elak Kena Hack DarkSword'  ->  96 comments  (total so far: 1,304)

  [OK] '2 benda menarik dengan Nothing Phone 4a 😍'  ->  6 comments  (total so far: 1,310)

  [OK] 'Phone Bajet RM4000 Makin MURAH Sale Raya 2026! 🔥'  ->  13 comments  (total so far: 1,323)

  [OK] 'Xiaomi Pad 8 Pro : Tablet Flagship Mampu Milik Paling Berbaloi 20'  ->  21 comments  (total so far: 1,344)

  [OK] 'Skrin OPPO Find N6 memang next level! 😨'  ->  6 comments  (total so far: 1,350)

  [OK] 'Smartphone Bajet RM2000 - RM3000 Paling Berbaloi Raya 2026!'  ->  42 comments  (total so far: 1,392)

  [OK] '5 Phone Bawah RM1000 TERBAIK Untuk Raya 2026!'  ->  33 comments  (total so far: 1,425)

  [OK] 'Benda best dengan iPhone 17e! 🥰'  ->  8 comments  (total so far: 1,433)

  [OK] '5 Smartphone RM3000 Lagi Berbaloi Dari iPhone 17e di Malaysia!'  ->  30 comments  (total so far: 1,463)

  [OK] 'Kekurangan iPhone 17e 🤭'  ->  37 comments  (total so far: 1,500)

  [OK] 'Jangan Beli iPhone 17e Dulu! Sebab…'  ->  33 comments  (total so far: 1,533)

  [OK] 'Phone siap ada gimbal camera! 😱 #HONORRobotPhone'  ->  13 comments  (total so far: 1,546)

  [OK] 'iQOO 15R : Flagship Gaming Mampu Milik PALING POWER! 🔥'  ->  45 comments  (total so far: 1,591)

  [OK] 'iPhone 17e dah sampai Malaysia! 🔥'  ->  26 comments  (total so far: 1,617)

  [OK] 'iPhone 17e Cubaan Kedua Yang Gagal?!'  ->  70 comments  (total so far: 1,687)

  [OK] 'HONOR Robot Phone Inovasi Gimbal Kamera Baru 2026!'  ->  29 comments  (total so far: 1,716)

  [OK] 'Robot Phone pertama dunia dengan kamera gimbal! #HONORRobotPhone'  ->  17 comments  (total so far: 1,733)

  [OK] 'Xiaomi 17 Ultra Terlalu Bagus? – Test Semua Fungsi Kamera Baru!'  ->  30 comments  (total so far: 1,763)

  [OK] 'iPhone pun kalah dengan Samsung S26 Ultra!'  ->  120 comments  (total so far: 1,883)

  [OK] 'Semua Yang Baru Dengan Samsung S26 / 26+ 🔥'  ->  19 comments  (total so far: 1,902)

  [OK] 'Samsung S26 Ultra Akhirnya Guna Skrin Baru! Tapi....'  ->  67 comments  (total so far: 1,969)

  [OK] 'iPhone 17e : iPhone TERMURAH 2026 Dengan Cip A19 Yang Power!'  ->  48 comments  (total so far: 2,017)

  [OK] 'Samsung S26 Ultra Dah Confirmed! Guna Design Baru? 😱'  ->  54 comments  (total so far: 2,071)

  [OK] 'Menyesal Beli GR Corolla? Review Lepas 3 Bulan 🔥'  ->  22 comments  (total so far: 2,093)

  [OK] '8 Phone Flagship BEST Masuk Malaysia Tahun 2026!'  ->  62 comments  (total so far: 2,155)

  [OK] 'iPhone 18 Kena CANCEL Tahun 2026! Sebab…'  ->  64 comments  (total so far: 2,219)

  [OK] '7 Jenama Phone Yang Stop Jual Phone!'  ->  291 comments  (total so far: 2,510)

  [OK] 'Tak Sangka iPhone Akan Jadi Android Juga Akhirnya...'  ->  63 comments  (total so far: 2,573)

  [OK] 'Selamat Tinggal ASUS ROG Phone 2026 😭'  ->  74 comments  (total so far: 2,647)

  [OK] 'Unboxing Studio Baru FUZZ 2026! 🔥'  ->  19 comments  (total so far: 2,666)

  [OK] 'Bukti Fon OPPO Makin Bagus! – OPPO Reno 15 5G'  ->  22 comments  (total so far: 2,688)

  [OK] 'Video iPhone 17 Pro Max tak cukup power? 🤔'  ->  5 comments  (total so far: 2,693)

  [OK] 'Apple pun kalah dengan Google? 😰'  ->  27 comments  (total so far: 2,720)

  [OK] 'REDMI Note 15 Pro+ 5G : Harga Mampu Milik Tapi Lebih Lasak!'  ->  34 comments  (total so far: 2,754)

  [OK] 'Xiaomi pun ada Smart Glasses 😎'  ->  9 comments  (total so far: 2,763)

  [OK] 'HUAWEI Mate X7 Buat Aku Lebih YAKIN Guna Foldable Phone!'  ->  17 comments  (total so far: 2,780)

  [OK] 'Sebab Samsung S25 Ultra Jadi Phone Terbaik 2025!'  ->  72 comments  (total so far: 2,852)

  [OK] 'Tablet Baru HUAWEI Yang Dah Rasa Macam Laptop! – MatePad 12X 2026'  ->  25 comments  (total so far: 2,877)

  [OK] 'Smartphone Terbaik 2025 Pilihan FUZZ 🔥'  ->  94 comments  (total so far: 2,971)

  [OK] 'Ini Sebab Ramai Beli Google Pixel 10 Pro di Malaysia!'  ->  29 comments  (total so far: 3,000)

Videos:   8%|▊         | 70/898 [00:30<06:02,  2.28video/s]

Reached 3,000 comment cap — stopping early.

Collection complete.
  Total comments collected : 3,000
  Videos skipped           : 1

## 9. Inspect the Raw Dataset

Before saving, we do a quick sanity check:
- Confirm the schema looks correct.
- Check for obvious issues such as blank comment text or duplicate comment IDs.
- Review the per-video comment distribution.

In [14]:
df_raw = pd.DataFrame(all_records)

print("=== Shape ===")
print(f"  Rows    : {df_raw.shape[0]:,}")
print(f"  Columns : {df_raw.shape[1]}")

print("\n=== Column types ===")
print(df_raw.dtypes)

print("\n=== Missing values ===")
print(df_raw.isnull().sum())

print("\n=== Duplicate comment IDs ===")
dupes = df_raw.duplicated(subset="comment_id").sum()
print(f"  {dupes} duplicate(s) found")

print("\n=== Sample rows ===")
df_raw[["video_title", "author", "comment_text", "like_count", "published_at"]].head(5)

=== Shape ===
  Rows    : 3,000
  Columns : 10

=== Column types ===
video_id                str
video_title             str
video_published_at      str
comment_id              str
author                  str
comment_text            str
like_count            int64
reply_count           int64
published_at            str
updated_at              str
dtype: object

=== Missing values ===
video_id              0
video_title           0
video_published_at    0
comment_id            0
author                0
comment_text          0
like_count            0
reply_count           0
published_at          0
updated_at            0
dtype: int64

=== Duplicate comment IDs ===
  0 duplicate(s) found

=== Sample rows ===

,video_title,author,comment_text,like_count,published_at
0,Aku Beli iPhone 17 Pro Harga RM200! Tak Sangka…,@zaimyim6168,dia ada cara.. utk youtube lepas bukak kasi pa...,1,2026-06-13T00:18:40Z
1,Aku Beli iPhone 17 Pro Harga RM200! Tak Sangka…,@mohdnidzwanabubakar2393,Buat backup ok kot hehehe,1,2026-06-12T23:20:15Z
2,Aku Beli iPhone 17 Pro Harga RM200! Tak Sangka…,@hafitdzkhairuddin4761,"IPhone 17 pro max kena sumpah..\n""Aku sumpah k...",0,2026-06-13T10:47:53Z
3,Aku Beli iPhone 17 Pro Harga RM200! Tak Sangka…,@HANKUROCHI,"Ni kalau boleh download ai ni ,ada yg bawak da...",0,2026-06-13T04:36:32Z
4,Aku Beli iPhone 17 Pro Harga RM200! Tak Sangka…,@nasrulfarid6826,Okay what beli untuk anak nice,0,2026-06-13T05:01:24Z

In [15]:
# Per-video comment count distribution
video_stats = (
    df_raw.groupby("video_title")["comment_id"]
    .count()
    .rename("comment_count")
    .sort_values(ascending=False)
    .reset_index()
)

print(f"Videos with collected comments: {len(video_stats)}")
print()
print("Top 10 most-commented videos:")
print(video_stats.head(10).to_string(index=False))

print("\nComment count stats:")
print(video_stats["comment_count"].describe().to_string())

Videos with collected comments: 69

Top 10 most-commented videos:
                                                        video_title  comment_count
                               7 Jenama Phone Yang Stop Jual Phone!            291
                       Lepas ni bateri phone boleh tukar sendiri? 🤔            170
                         iPhone pun kalah dengan Samsung S26 Ultra!            120
                   Unboxing iPhone 18 Pro Pertama di Planet Bumi! 🔥            119
iPhone Dah Tak Selamat? – Update Penting Elak Kena Hack DarkSword 🔥             96
                             Smartphone Terbaik 2025 Pilihan FUZZ 🔥             94
                   iPhone SEDAP Guna Tahun 2026 ~ 2027 Makin Murah!             91
                              Selamat Tinggal ASUS ROG Phone 2026 😭             74
                   Sebab Samsung S25 Ultra Jadi Phone Terbaik 2025!             72
                               iPhone 17e Cubaan Kedua Yang Gagal?!             70

Comment count stats:
count     69.000000
mean      43.478261
std       43.160647
min        3.000000
25%       20.000000
50%       32.000000
75%       58.000000
max      291.000000

## 10. Save Raw Data

We save the unmodified DataFrame to `data/raw_data/youtube_comments_raw.csv`.

- **UTF-8-sig** encoding is used so the file opens correctly in Excel (adds a BOM marker).
- The index is excluded (`index=False`) to keep the CSV clean.
- A **metadata JSON sidecar** is written alongside the CSV to document when and how the data was collected — useful for reproducibility.

In [16]:
# Save CSV
df_raw.to_csv(OUTPUT_FILE, index=False, encoding="utf-8-sig")
print(f"Raw CSV saved  -> {os.path.abspath(OUTPUT_FILE)}")
print(f"  Rows : {len(df_raw):,}")
print(f"  Size : {os.path.getsize(OUTPUT_FILE) / 1024:.1f} KB")

# Save collection metadata sidecar
metadata = {
    "collected_at"       : datetime.utcnow().isoformat() + "Z",
    "channel_title"      : CHANNEL_TITLE,
    "channel_id"         : CHANNEL_ID,
    "uploads_playlist"   : UPLOADS_PLAYLIST_ID,
    "total_channel_vids" : len(all_videos),
    "phone_review_vids"  : len(phone_videos),
    "videos_skipped"     : len(skipped),
    "total_comments"     : len(df_raw),
    "phone_keywords"     : PHONE_KEYWORDS,
    "output_file"        : os.path.abspath(OUTPUT_FILE),
}

meta_file = OUTPUT_FILE.replace(".csv", "_metadata.json")
with open(meta_file, "w", encoding="utf-8") as fh:
    json.dump(metadata, fh, indent=2)

print(f"Metadata saved -> {os.path.abspath(meta_file)}")

Raw CSV saved  -> c:\UTM things\Year 3\SEM 2\HDPD\Project 2\data\raw_data\youtube_comments_raw.csv
  Rows : 3,000
  Size : 769.9 KB
Metadata saved -> c:\UTM things\Year 3\SEM 2\HDPD\Project 2\data\raw_data\youtube_comments_raw_metadata.json

## 11. Collection Summary

The table below summarises what was collected in this run.

In [18]:
summary = pd.DataFrame([
    {"Metric": "Channel",                        "Value": CHANNEL_TITLE},
    {"Metric": "Total videos on channel",         "Value": str(len(all_videos))},
    {"Metric": "Smartphone review videos",        "Value": str(len(phone_videos))},
    {"Metric": "Videos with comments collected",  "Value": str(len(phone_videos) - len(skipped))},
    {"Metric": "Videos skipped (no comments)",    "Value": str(len(skipped))},
    {"Metric": "Total comments collected",        "Value": f"{len(df_raw):,}"},
    {"Metric": "Unique videos in dataset",        "Value": str(df_raw['video_id'].nunique())},
    {"Metric": "Output file",                     "Value": OUTPUT_FILE},
])

summary.index = [""] * len(summary)
display(summary)

,Metric,Value
,Channel,FUZZ CHANNEL
,Total videos on channel,1246
,Smartphone review videos,898
,Videos with comments collected,897
,Videos skipped (no comments),1
,Total comments collected,"3,000"
,Unique videos in dataset,69
,Output file,c:\UTM things\Year 3\SEM 2\HDPD\Project 2\data...