# YouTube Comment Collection — FUZZ CHANNEL

**Project 2 | High Performance Data Processing (SECP3133)**  
**Data Source:** YouTube comments from all videos on FUZZ CHANNEL (Malaysian tech review channel)

---

This notebook collects raw YouTube comments from **all videos** published on **FUZZ CHANNEL**. The collected comments serve as the primary text corpus for downstream sentiment analysis.

### Pipeline overview

Youtube Data API v3 -> Channel ID -> Fetch Comments (Paginated) -> Save into **data/raw_data/youtube_comments_raw.csv**

### Collected fields
| Field | Description |
|---|---|
| `video_id` | YouTube video identifier |
| `video_title` | Title of the video |
| `video_published_at` | Upload date of the video |
| `comment_id` | Unique comment identifier |
| `author` | Display name of the commenter |
| `comment_text` | Raw comment text |
| `like_count` | Number of likes on the comment |
| `reply_count` | Number of replies to the comment thread |
| `published_at` | Timestamp the comment was posted |
| `updated_at` | Timestamp of last edit (if any) |

## 1. Setup and Imports

We rely on the following libraries:

- **`google-api-python-client`** — official Google client library wrapping the YouTube Data API v3.
- **`pandas`** — tabular data manipulation and CSV export.
- **`tqdm`** — lightweight progress bars for long-running loops.
- **`time` / `datetime`** — rate-limit back-off and timestamping.

> Install any missing package with: `pip install google-api-python-client pandas tqdm`

In [1]:
import os
import time
import json
from datetime import datetime

import pandas as pd
from tqdm import tqdm
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

print("Libraries loaded successfully.")

Libraries loaded successfully.

## 2. Configuration

Set your YouTube Data API v3 key and the collection parameters below.

| Parameter | Purpose |
|---|---|
| `API_KEY` | Authenticates requests to the YouTube Data API. |
| `CHANNEL_QUERY` | Search term used to locate FUZZ CHANNEL. |
| `MAX_COMMENTS_PER_VIDEO` | Upper bound on comments fetched per video (`None` = all). |
| `MAX_TOTAL_COMMENTS` | Hard cap on total comments collected across all videos. |
| `REQUEST_DELAY` | Seconds to wait between API calls to avoid quota bursts. |
| `OUTPUT_DIR` | Directory where the raw CSV will be written. |

> **Quota note:** The YouTube Data API v3 grants **10,000 units per day** on a free key.  
> Each `commentThreads.list` call costs **1 unit** and returns up to 100 comments.  
> With 10,000 units you can pull roughly 1,000,000 comments — more than enough for this project.

In [ ]:
# ── Authentication ─────────────────────────────────────────────────────────────
API_KEY = "YOUR_API_KEY_HERE"

# ── Channel targeting ──────────────────────────────────────────────────────────
CHANNEL_QUERY = "FUZZ CHANNEL"

# ── Collection limits ──────────────────────────────────────────────────────────
MAX_COMMENTS_PER_VIDEO = None
MAX_TOTAL_COMMENTS     = 12000
REQUEST_DELAY          = 0.3    # seconds between API calls

# ── Output ─────────────────────────────────────────────────────────────────────
OUTPUT_DIR  = r"c:\UTM things\Year 3\SEM 2\HDPD\Project 2\data\raw_data"
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "youtube_comments_raw.csv")

os.makedirs(OUTPUT_DIR, exist_ok=True)
print(f"Output directory: {os.path.abspath(OUTPUT_DIR)}")

Output directory: c:\UTM things\Year 3\SEM 2\HDPD\Project 2\data\raw_data

## 3. Build the API Client

`googleapiclient.discovery.build` constructs a service object for the YouTube Data API v3.  
All subsequent calls go through this single client instance.

In [3]:
youtube = build("youtube", "v3", developerKey=API_KEY)
print("YouTube API client ready.")

YouTube API client ready.

## 4. Locate FUZZ CHANNEL

We use the **`search.list`** endpoint with `type=channel` to find FUZZ CHANNEL and retrieve its unique **channel ID**.  
The channel ID is then used to access the channel's upload playlist.

The **`channels.list`** endpoint returns a `contentDetails.relatedPlaylists.uploads` field — a special playlist that contains every video the channel has ever uploaded, in reverse-chronological order.

In [4]:
def get_channel_id(youtube_client, query):
    """
    Search for a YouTube channel by name and return (channel_id, channel_title).
    Raises ValueError if no channel is found.
    """
    response = youtube_client.search().list(
        q=query,
        type="channel",
        part="snippet",
        maxResults=5,
    ).execute()

    items = response.get("items", [])
    if not items:
        raise ValueError(f"No channel found for query: '{query}'")

    # Print all candidates so we can verify we picked the right one
    print("Candidate channels found:")
    for i, item in enumerate(items):
        cid   = item["snippet"]["channelId"]
        title = item["snippet"]["title"]
        print(f"  [{i}] {title}  (id: {cid})")

    channel_id    = items[0]["snippet"]["channelId"]
    channel_title = items[0]["snippet"]["title"]
    return channel_id, channel_title


def get_uploads_playlist_id(youtube_client, channel_id):
    """
    Return the uploads playlist ID for a given channel.
    This playlist contains all videos uploaded to the channel.
    """
    response = youtube_client.channels().list(
        id=channel_id,
        part="contentDetails",
    ).execute()

    return response["items"][0]["contentDetails"]["relatedPlaylists"]["uploads"]


# ── Execute ────────────────────────────────────────────────────────────────────
CHANNEL_ID, CHANNEL_TITLE = get_channel_id(youtube, CHANNEL_QUERY)
UPLOADS_PLAYLIST_ID       = get_uploads_playlist_id(youtube, CHANNEL_ID)

print(f"\nSelected channel : {CHANNEL_TITLE}")
print(f"Channel ID       : {CHANNEL_ID}")
print(f"Uploads playlist : {UPLOADS_PLAYLIST_ID}")

Candidate channels found:
  [0] FUZZ CHANNEL  (id: UCNgBXwadunmKRt0TksSFaqw)
  [1] Fuzz  (id: UCk_YaS7EjbnUe6r_1colvlA)
  [2] More Fuzz  (id: UC_I3PBtw880M77iQWKUY1Fg)
  [3] fuzz  (id: UCGacX4lqGSqYXZjnXrDPTOg)
  [4] Fakkah Fuzz  (id: UCMiaHiq_gGSe1vn-RqXZTog)

Selected channel : FUZZ CHANNEL
Channel ID       : UCNgBXwadunmKRt0TksSFaqw
Uploads playlist : UUNgBXwadunmKRt0TksSFaqw

## 5. Fetch All Uploaded Videos

The **`playlistItems.list`** endpoint is the most efficient way to enumerate a channel's videos.  
It returns up to **50 items per page**, so we paginate using `nextPageToken` until all pages are exhausted.

For each video we capture:
- `video_id` — needed to fetch its comments
- `video_title` — stored alongside each comment for reference and analysis
- `video_published_at` — for time-series analysis later

In [5]:
def fetch_all_videos(youtube_client, playlist_id):
    """
    Paginate through a playlist and return a list of video metadata dicts.
    Each dict contains: video_id, video_title, video_published_at.
    """
    videos     = []
    page_token = None

    print("Fetching video list from uploads playlist ...")
    while True:
        request_kwargs = dict(
            playlistId=playlist_id,
            part="snippet,contentDetails",
            maxResults=50,
        )
        if page_token:
            request_kwargs["pageToken"] = page_token

        response   = youtube_client.playlistItems().list(**request_kwargs).execute()
        page_items = response.get("items", [])

        for item in page_items:
            snippet = item["snippet"]
            videos.append({
                "video_id"           : snippet["resourceId"]["videoId"],
                "video_title"        : snippet.get("title", ""),
                "video_published_at" : snippet.get("publishedAt", ""),
            })

        page_token = response.get("nextPageToken")
        if not page_token:
            break

        time.sleep(REQUEST_DELAY)

    print(f"Total videos found: {len(videos)}")
    return videos


all_videos = fetch_all_videos(youtube, UPLOADS_PLAYLIST_ID)

Fetching video list from uploads playlist ...
Total videos found: 1248

## 6. Prepare Video List

All videos from the channel's uploads playlist are used. No filtering is applied — comments will be collected across the full range of FUZZ CHANNEL content, which covers tech reviews, tips, comparisons, and general tech news.

In [6]:
target_videos = all_videos

print(f"Total videos on channel : {len(all_videos)}")
print(f"Videos to collect from  : {len(target_videos)}")
print()
print("Sample videos:")
for v in target_videos[:10]:
    print(f"  [{v['video_published_at'][:10]}] {v['video_title']}")

Total videos on channel : 1248
Videos to collect from  : 1248

Sample videos:
  [2026-06-18] Selamat Tinggal iPad... Dah Jumpa Tablet Lagi Murah Yang Power!
  [2026-06-15] Brand Smartphone Yang Bukan Buat Phone Je! Tapi...
  [2026-06-11] Aku Beli iPhone 17 Pro Harga RM200! Tak Sangka…
  [2026-06-11] iPhone aku dah update iOS 27 😍
  [2026-06-11] iOS 27 vs iOS 26 : Clean Up 🔥
  [2026-06-09] iOS 27 dah rasmi dengan Siri AI 🎉
  [2026-06-09] Semua Ciri Baru iOS 27 Pengguna iPhone Wajib Tahu!
  [2026-06-05] HONOR Magic V6 Dah Boleh Connect iOS 27 Ecosystem!
  [2026-06-03] Social Media Kena Banned : 16 Tahun Ke Bawah Tak Boleh Guna! 🔥
  [2026-05-30] 25 Fungsi Menarik iPhone Tak Ramai Tahu!

## 7. Comment Collection — Helper Function

For each video we call **`commentThreads.list`**, which returns top-level comment threads.

### Pagination
The endpoint returns a maximum of **100 comments per page**. We loop on `nextPageToken` until either:
- There are no more pages, or
- We have reached `MAX_COMMENTS_PER_VIDEO` (if set).

### Error handling
| HTTP error | Cause | Action |
|---|---|---|
| 403 `commentsDisabled` | Channel/video has comments turned off | Skip video, log warning |
| 403 `forbidden` | Video is private or age-restricted | Skip video, log warning |
| 404 | Video deleted after playlist was fetched | Skip video, log warning |
| 429 / 5xx | Quota exhausted or server error | Raise immediately |

In [7]:
def fetch_comments_for_video(youtube_client, video_id, max_comments=None):
    """
    Fetch all top-level comments for a single video.

    Returns a list of comment dicts.
    Returns an empty list if comments are disabled or the video is unavailable.
    """
    comments   = []
    page_token = None

    while True:
        try:
            request_kwargs = dict(
                videoId=video_id,
                part="snippet",
                maxResults=100,
                textFormat="plainText",
                order="relevance",
            )
            if page_token:
                request_kwargs["pageToken"] = page_token

            response = youtube_client.commentThreads().list(**request_kwargs).execute()

        except HttpError as e:
            error_reason = ""
            try:
                error_body   = json.loads(e.content)
                error_reason = error_body["error"]["errors"][0]["reason"]
            except Exception:
                pass

            if e.resp.status in (403, 404):
                # Comments disabled, private video, or age-restricted — skip gracefully
                print(f"    [SKIP] {video_id}: {error_reason or e.resp.status}")
                return []
            else:
                raise  # Re-raise unexpected errors (quota exhausted, server errors)

        for item in response.get("items", []):
            top = item["snippet"]["topLevelComment"]["snippet"]
            comments.append({
                "comment_id"   : item["snippet"]["topLevelComment"]["id"],
                "author"       : top.get("authorDisplayName", ""),
                "comment_text" : top.get("textDisplay", ""),
                "like_count"   : top.get("likeCount", 0),
                "reply_count"  : item["snippet"].get("totalReplyCount", 0),
                "published_at" : top.get("publishedAt", ""),
                "updated_at"   : top.get("updatedAt", ""),
            })

        # Check early-stop condition
        if max_comments and len(comments) >= max_comments:
            comments = comments[:max_comments]
            break

        page_token = response.get("nextPageToken")
        if not page_token:
            break

        time.sleep(REQUEST_DELAY)

    return comments


print("Comment fetcher defined.")

Comment fetcher defined.

## 8. Run the Collection Loop

Iterate over all videos and accumulate comments into a single flat list, stopping once the `MAX_TOTAL_COMMENTS` cap is reached.  
A `tqdm` progress bar tracks per-video progress, and running totals are printed after each video.

In [8]:
all_records = []
skipped     = []

print(f"Starting collection for {len(target_videos)} videos (cap: {MAX_TOTAL_COMMENTS:,} total comments) ...\n")

for video in tqdm(target_videos, desc="Videos", unit="video"):
    if len(all_records) >= MAX_TOTAL_COMMENTS:
        print(f"\nReached {MAX_TOTAL_COMMENTS:,} comment cap — stopping early.")
        break

    vid_id    = video["video_id"]
    vid_title = video["video_title"]

    remaining = MAX_TOTAL_COMMENTS - len(all_records)

    comments = fetch_comments_for_video(
        youtube,
        video_id=vid_id,
        max_comments=remaining,
    )

    if not comments:
        skipped.append(vid_id)
        continue

    for comment in comments:
        all_records.append({
            "video_id"           : vid_id,
            "video_title"        : vid_title,
            "video_published_at" : video["video_published_at"],
            **comment,
        })

    print(
        f"  [OK] {vid_title[:65]!r}  ->  {len(comments):,} comments  "
        f"(total so far: {len(all_records):,})"
    )
    time.sleep(REQUEST_DELAY)

print(f"\nCollection complete.")
print(f"  Total comments collected : {len(all_records):,}")
print(f"  Videos skipped           : {len(skipped)}")

Starting collection for 1248 videos (cap: 12,000 total comments) ...

Videos:   0%|          | 0/1248 [00:00<?, ?video/s]

  [OK] 'Selamat Tinggal iPad... Dah Jumpa Tablet Lagi Murah Yang Power!'  ->  35 comments  (total so far: 35)

Videos:   0%|          | 1/1248 [00:00<08:23,  2.47video/s]

  [OK] 'Brand Smartphone Yang Bukan Buat Phone Je! Tapi...'  ->  14 comments  (total so far: 49)

Videos:   0%|          | 2/1248 [00:00<08:05,  2.57video/s]

  [OK] 'Aku Beli iPhone 17 Pro Harga RM200! Tak Sangka…'  ->  63 comments  (total so far: 112)

Videos:   0%|          | 3/1248 [00:01<08:30,  2.44video/s]

  [OK] 'iPhone aku dah update iOS 27 😍'  ->  5 comments  (total so far: 117)

Videos:   0%|          | 4/1248 [00:01<08:36,  2.41video/s]

  [OK] 'iOS 27 vs iOS 26 : Clean Up 🔥'  ->  9 comments  (total so far: 126)

Videos:   0%|          | 5/1248 [00:02<08:32,  2.42video/s]

  [OK] 'iOS 27 dah rasmi dengan Siri AI 🎉'  ->  8 comments  (total so far: 134)

Videos:   0%|          | 6/1248 [00:02<08:36,  2.40video/s]

  [OK] 'Semua Ciri Baru iOS 27 Pengguna iPhone Wajib Tahu!'  ->  24 comments  (total so far: 158)

Videos:   1%|          | 7/1248 [00:02<08:52,  2.33video/s]

  [OK] 'HONOR Magic V6 Dah Boleh Connect iOS 27 Ecosystem!'  ->  13 comments  (total so far: 171)

Videos:   1%|          | 8/1248 [00:03<08:45,  2.36video/s]

  [OK] 'Social Media Kena Banned : 16 Tahun Ke Bawah Tak Boleh Guna! 🔥'  ->  48 comments  (total so far: 219)

Videos:   1%|          | 9/1248 [00:03<08:57,  2.31video/s]

  [OK] '25 Fungsi Menarik iPhone Tak Ramai Tahu!'  ->  33 comments  (total so far: 252)

Videos:   1%|          | 10/1248 [00:04<09:10,  2.25video/s]

  [OK] 'Xiaomi 17T Pro Terlalu Bagus Untuk Harga Bawah RM3000!'  ->  34 comments  (total so far: 286)

Videos:   1%|          | 11/1248 [00:04<08:44,  2.36video/s]

  [OK] 'HONOR Tipu Buat Stress Test Foldable Magic V6?'  ->  22 comments  (total so far: 308)

Videos:   1%|          | 12/1248 [00:05<08:52,  2.32video/s]

  [OK] 'Tiba-tiba dah iOS 27 😆'  ->  12 comments  (total so far: 320)

Videos:   1%|          | 13/1248 [00:05<08:46,  2.35video/s]

  [OK] 'Benda Penting Pasal iOS 27 + iPhone Ultra! 🔥'  ->  24 comments  (total so far: 344)

Videos:   1%|          | 14/1248 [00:05<09:02,  2.27video/s]

  [OK] 'Rahsia Aku Kurus Dari 100KG Drop Sampai 80KG Sambil Guna HUAWEI W'  ->  24 comments  (total so far: 368)

Videos:   1%|          | 15/1248 [00:06<09:55,  2.07video/s]

  [OK] 'FUZZ main forex? 🤔'  ->  46 comments  (total so far: 414)

Videos:   1%|▏         | 16/1248 [00:07<09:43,  2.11video/s]

  [OK] 'Sebab iPhone 17 paling laku sekarang 😱'  ->  47 comments  (total so far: 461)

Videos:   1%|▏         | 17/1248 [00:07<09:44,  2.11video/s]

  [OK] 'Fon Flagship Bawah RM2000 Paling Power! – POCO X8 Pro Max Malaysi'  ->  54 comments  (total so far: 515)

Videos:   1%|▏         | 18/1248 [00:08<10:12,  2.01video/s]

  [OK] 'Punca Nintendo Switch 2 Naik Harga Mengarut! – Waktu Sesuai Beli?'  ->  31 comments  (total so far: 546)

Videos:   2%|▏         | 19/1248 [00:08<09:41,  2.12video/s]

  [OK] 'iPhone 17 Review : Phone Paling Laris 2026!'  ->  69 comments  (total so far: 615)

Videos:   2%|▏         | 20/1248 [00:08<09:40,  2.12video/s]

  [OK] 'iPhone Ultra foldable pertama Apple dah confirmed?! 😱'  ->  20 comments  (total so far: 635)

Videos:   2%|▏         | 21/1248 [00:09<09:19,  2.19video/s]

  [OK] 'iPhone SEDAP Guna Tahun 2026 ~ 2027 Makin Murah!'  ->  91 comments  (total so far: 726)

Videos:   2%|▏         | 22/1248 [00:09<09:12,  2.22video/s]

  [OK] 'iPhone Ultra Dah Confirmed?! – Foldable Pertama Apple Harga RM10,'  ->  20 comments  (total so far: 746)

Videos:   2%|▏         | 23/1248 [00:10<08:58,  2.28video/s]

  [OK] 'Lepas ni bateri phone boleh tukar sendiri? 🤔'  ->  169 comments  (total so far: 915)

Videos:   2%|▏         | 24/1248 [00:11<12:22,  1.65video/s]

  [OK] 'OPPO Find X9 Ultra : Sebuah Kamera Dalam Badan Smartphone'  ->  16 comments  (total so far: 931)

Videos:   2%|▏         | 25/1248 [00:11<11:08,  1.83video/s]

  [OK] 'VIVO X300 Ultra Pertama Kali Masuk Malaysia!'  ->  22 comments  (total so far: 953)

Videos:   2%|▏         | 26/1248 [00:12<10:28,  1.95video/s]

  [OK] '10 Smartphone Dengan Bateri Besar Tak Masuk Akal! 🔥'  ->  35 comments  (total so far: 988)

Videos:   2%|▏         | 27/1248 [00:12<09:54,  2.05video/s]

  [OK] 'OPPO Find X9 Ultra Terlalu Bagus Sampai iPhone 17 Pro Kena Tingga'  ->  27 comments  (total so far: 1,015)

Videos:   2%|▏         | 29/1248 [00:13<07:59,  2.54video/s]

  [OK] 'HONOR 600 Pro Tiru iPhone 17 Pro? – Banyak Benda Ramai Tak Tahu!'  ->  28 comments  (total so far: 1,043)

Videos:   2%|▏         | 30/1248 [00:13<07:58,  2.54video/s]

  [OK] 'Sebab Tim Cook Tinggalkan Apple! – Perubahan Besar Akan Berlaku?!'  ->  65 comments  (total so far: 1,108)

Videos:   2%|▏         | 31/1248 [00:13<08:13,  2.46video/s]

  [OK] 'Macam Ni Rasanya Guna Tandas Jepun Kat Rumah Sendiri!'  ->  8 comments  (total so far: 1,116)

Videos:   3%|▎         | 32/1248 [00:14<08:06,  2.50video/s]

  [OK] 'Harap semuanya jelas 😔'  ->  79 comments  (total so far: 1,195)

Videos:   3%|▎         | 33/1248 [00:14<09:07,  2.22video/s]

  [OK] 'HONOR 600 Pro Makin Mengganas Dengan Flagship Mampu Milik!'  ->  39 comments  (total so far: 1,234)

Videos:   3%|▎         | 34/1248 [00:15<08:52,  2.28video/s]

  [OK] 'Just nak bagi pencerahan'  ->  47 comments  (total so far: 1,281)

Videos:   3%|▎         | 35/1248 [00:15<08:55,  2.27video/s]

  [OK] 'OPPO Find X9 Ultra : Pencabar Hebat Xiaomi & VIVO Ultra di Malays'  ->  36 comments  (total so far: 1,317)

Videos:   3%|▎         | 36/1248 [00:16<08:58,  2.25video/s]

  [OK] 'vivo V70 FE : Fon Bajet RM1500 Boleh Dapat Kamera 200MP!'  ->  18 comments  (total so far: 1,335)

Videos:   3%|▎         | 37/1248 [00:16<08:45,  2.31video/s]

  [OK] 'iPhone 600 Pro atau HONOR 17 Pro? 🤔'  ->  9 comments  (total so far: 1,344)

Videos:   3%|▎         | 38/1248 [00:17<12:42,  1.59video/s]

  [OK] 'Unboxing iPhone 18 Pro Pertama di Planet Bumi! 🔥'  ->  119 comments  (total so far: 1,463)

Videos:   3%|▎         | 39/1248 [00:18<14:17,  1.41video/s]

  [OK] 'MacBook Neo vs Air vs Pro 🔥'  ->  11 comments  (total so far: 1,474)

Videos:   3%|▎         | 40/1248 [00:18<12:27,  1.62video/s]

  [OK] 'Samsung Galaxy A37 vs A57 : Patut Beli Mana Satu?'  ->  59 comments  (total so far: 1,533)

Videos:   3%|▎         | 41/1248 [00:19<11:12,  1.80video/s]

  [OK] 'MacBook Neo Dah Sampai Malaysia Harga RM2499! – Sesuai Untuk Siap'  ->  26 comments  (total so far: 1,559)

Videos:   3%|▎         | 42/1248 [00:19<10:19,  1.95video/s]

  [OK] 'iPhone 17 Pro Max naik rocket sampai angkas lepas! 😱'  ->  32 comments  (total so far: 1,591)

Videos:   3%|▎         | 43/1248 [00:20<10:02,  2.00video/s]

  [OK] 'Kamera realme 16 Pro+ 5G Kali Ni Memang ANOTHER LEVEL!'  ->  24 comments  (total so far: 1,615)

Videos:   4%|▎         | 44/1248 [00:20<09:17,  2.16video/s]

  [OK] 'Musim minyak naik harga & hujan ni layan sim racing jela 😅'  ->  7 comments  (total so far: 1,622)

Videos:   4%|▎         | 45/1248 [00:21<08:55,  2.25video/s]

  [OK] 'Aku Setup SIM RACING Bajet RM5000 Dan Hasilnya Memang…🔥'  ->  79 comments  (total so far: 1,701)

Videos:   4%|▎         | 46/1248 [00:21<09:13,  2.17video/s]

  [OK] 'Dah Jumpa Washer Dryer Yang BERBALOI Guna Untuk Tahun Ini!'  ->  28 comments  (total so far: 1,729)

Videos:   4%|▍         | 47/1248 [00:21<08:54,  2.25video/s]

  [OK] 'Samsung dah boleh AirDrop / Quick Share dengan iPhone!'  ->  3 comments  (total so far: 1,732)

Videos:   4%|▍         | 48/1248 [00:22<08:38,  2.32video/s]

  [OK] 'Nothing Phone 4a Pro Akhirnya Berubah!'  ->  59 comments  (total so far: 1,791)

Videos:   4%|▍         | 49/1248 [00:22<08:45,  2.28video/s]

  [OK] 'Update iPhone korang sekarang dari kena hack!'  ->  33 comments  (total so far: 1,824)

Videos:   4%|▍         | 50/1248 [00:23<08:38,  2.31video/s]

  [OK] 'iPhone Dah Tak Selamat? – Update Penting Elak Kena Hack DarkSword'  ->  96 comments  (total so far: 1,920)

Videos:   4%|▍         | 51/1248 [00:23<09:09,  2.18video/s]

  [OK] '2 benda menarik dengan Nothing Phone 4a 😍'  ->  6 comments  (total so far: 1,926)

Videos:   4%|▍         | 52/1248 [00:24<08:57,  2.22video/s]

  [OK] 'Phone Bajet RM4000 Makin MURAH Sale Raya 2026! 🔥'  ->  13 comments  (total so far: 1,939)

Videos:   4%|▍         | 53/1248 [00:24<08:39,  2.30video/s]

  [OK] 'Xiaomi Pad 8 Pro : Tablet Flagship Mampu Milik Paling Berbaloi 20'  ->  19 comments  (total so far: 1,958)

Videos:   4%|▍         | 54/1248 [00:24<08:19,  2.39video/s]

  [OK] 'Skrin OPPO Find N6 memang next level! 😨'  ->  6 comments  (total so far: 1,964)

Videos:   4%|▍         | 55/1248 [00:25<08:20,  2.38video/s]

  [OK] 'Smartphone Bajet RM2000 - RM3000 Paling Berbaloi Raya 2026!'  ->  42 comments  (total so far: 2,006)

Videos:   4%|▍         | 56/1248 [00:25<08:25,  2.36video/s]

  [OK] '5 Phone Bawah RM1000 TERBAIK Untuk Raya 2026!'  ->  33 comments  (total so far: 2,039)

Videos:   5%|▍         | 57/1248 [00:26<08:24,  2.36video/s]

  [OK] 'Benda best dengan iPhone 17e! 🥰'  ->  8 comments  (total so far: 2,047)

Videos:   5%|▍         | 58/1248 [00:26<08:19,  2.38video/s]

  [OK] '5 Smartphone RM3000 Lagi Berbaloi Dari iPhone 17e di Malaysia!'  ->  26 comments  (total so far: 2,073)

Videos:   5%|▍         | 59/1248 [00:27<08:23,  2.36video/s]

  [OK] 'Insta360 X5 masih best guna tahun 2026? 🤔'  ->  1 comments  (total so far: 2,074)

Videos:   5%|▍         | 60/1248 [00:27<08:20,  2.37video/s]

  [OK] 'Kekurangan iPhone 17e 🤭'  ->  37 comments  (total so far: 2,111)

Videos:   5%|▍         | 61/1248 [00:27<08:19,  2.38video/s]

  [OK] 'Jangan Beli iPhone 17e Dulu! Sebab…'  ->  31 comments  (total so far: 2,142)

Videos:   5%|▍         | 62/1248 [00:28<08:18,  2.38video/s]

  [OK] 'Phone siap ada gimbal camera! 😱 #HONORRobotPhone'  ->  13 comments  (total so far: 2,155)

Videos:   5%|▌         | 63/1248 [00:28<08:40,  2.28video/s]

  [OK] 'Robot manusia yang kecik comel, tapi lincah! 🤖'  ->  72 comments  (total so far: 2,227)

Videos:   5%|▌         | 64/1248 [00:29<08:56,  2.21video/s]

  [OK] 'MacBook Neo MURAH Tak Masuk Akal RM2499 Je! Berbaloi Beli? 🤔'  ->  22 comments  (total so far: 2,249)

Videos:   5%|▌         | 65/1248 [00:29<08:52,  2.22video/s]

  [OK] 'Gajet MENARIK Yang BERBALOI Beli Tahun 2026! – EP2'  ->  17 comments  (total so far: 2,266)

Videos:   5%|▌         | 66/1248 [00:30<08:44,  2.26video/s]

  [OK] 'iQOO 15R : Flagship Gaming Mampu Milik PALING POWER! 🔥'  ->  45 comments  (total so far: 2,311)

Videos:   5%|▌         | 67/1248 [00:30<08:29,  2.32video/s]

  [OK] 'iPhone 17e dah sampai Malaysia! 🔥'  ->  26 comments  (total so far: 2,337)

Videos:   5%|▌         | 68/1248 [00:30<08:33,  2.30video/s]

  [OK] 'Robot pun boleh buat backflip 😨'  ->  21 comments  (total so far: 2,358)

Videos:   6%|▌         | 69/1248 [00:31<08:33,  2.30video/s]

  [OK] 'iPhone 17e Cubaan Kedua Yang Gagal?!'  ->  70 comments  (total so far: 2,428)

Videos:   6%|▌         | 70/1248 [00:31<08:49,  2.22video/s]

  [OK] 'HONOR Robot Phone Inovasi Gimbal Kamera Baru 2026!'  ->  29 comments  (total so far: 2,457)

Videos:   6%|▌         | 71/1248 [00:32<08:51,  2.22video/s]

  [OK] 'Robot Phone pertama dunia dengan kamera gimbal! #HONORRobotPhone'  ->  17 comments  (total so far: 2,474)

Videos:   6%|▌         | 72/1248 [00:32<09:39,  2.03video/s]

  [OK] 'Xiaomi 17 Ultra Terlalu Bagus? – Test Semua Fungsi Kamera Baru!'  ->  31 comments  (total so far: 2,505)

Videos:   6%|▌         | 73/1248 [00:33<09:21,  2.09video/s]

  [OK] 'iPhone pun kalah dengan Samsung S26 Ultra!'  ->  120 comments  (total so far: 2,625)

Videos:   6%|▌         | 74/1248 [00:34<11:57,  1.64video/s]

  [OK] 'Semua Yang Baru Dengan Samsung S26 / 26+ 🔥'  ->  19 comments  (total so far: 2,644)

Videos:   6%|▌         | 75/1248 [00:34<10:53,  1.79video/s]

  [OK] 'Samsung S26 Ultra Akhirnya Guna Skrin Baru! Tapi....'  ->  67 comments  (total so far: 2,711)

Videos:   6%|▌         | 76/1248 [00:35<10:20,  1.89video/s]

  [OK] 'Kerja sambil berpuasa di San Francisco US 😁'  ->  12 comments  (total so far: 2,723)

Videos:   6%|▌         | 77/1248 [00:35<11:04,  1.76video/s]

  [OK] '7 tahun dah bersama YouTube 🥹🙏'  ->  68 comments  (total so far: 2,791)

Videos:   6%|▋         | 78/1248 [00:36<10:30,  1.85video/s]

  [OK] 'VLOG First Time Pergi TOKYO JAPAN Musim Sejuk!'  ->  29 comments  (total so far: 2,820)

Videos:   6%|▋         | 79/1248 [00:36<09:46,  1.99video/s]

  [OK] 'iPhone 17e : iPhone TERMURAH 2026 Dengan Cip A19 Yang Power!'  ->  48 comments  (total so far: 2,868)

Videos:   6%|▋         | 80/1248 [00:37<09:53,  1.97video/s]

  [OK] 'Samsung S26 Ultra Dah Confirmed! Guna Design Baru? 😱'  ->  54 comments  (total so far: 2,922)

Videos:   6%|▋         | 81/1248 [00:37<09:35,  2.03video/s]

  [OK] 'Menyesal Beli GR Corolla? Review Lepas 3 Bulan 🔥'  ->  22 comments  (total so far: 2,944)

Videos:   7%|▋         | 82/1248 [00:38<09:13,  2.11video/s]

  [OK] 'DJI Osmo Pocket 4 dah nak keluar! 🔥'  ->  1 comments  (total so far: 2,945)

Videos:   7%|▋         | 83/1248 [00:38<08:59,  2.16video/s]

  [OK] '8 Phone Flagship BEST Masuk Malaysia Tahun 2026!'  ->  62 comments  (total so far: 3,007)

Videos:   7%|▋         | 84/1248 [00:39<09:04,  2.14video/s]

  [OK] '16 tahun ke bawah tak boleh guna social media?! 😱'  ->  29 comments  (total so far: 3,036)

Videos:   7%|▋         | 85/1248 [00:39<08:53,  2.18video/s]

  [OK] 'FUZZ Jual Balik Proton Saga MC3? Ada Masalah Lepas 2 Bulan?'  ->  113 comments  (total so far: 3,149)

Videos:   7%|▋         | 86/1248 [00:40<11:54,  1.63video/s]

  [OK] 'iPhone 18 Kena CANCEL Tahun 2026! Sebab…'  ->  64 comments  (total so far: 3,213)

Videos:   7%|▋         | 87/1248 [00:40<11:08,  1.74video/s]

  [OK] 'Shot paling aesthetic pernah aku dapat 😅'  ->  7 comments  (total so far: 3,220)

Videos:   7%|▋         | 88/1248 [00:41<10:15,  1.89video/s]

  [OK] 'VLOG New Zealand : Explore Queenstown, Hobbiton & Auckland! (Part'  ->  18 comments  (total so far: 3,238)

Videos:   7%|▋         | 89/1248 [00:41<10:09,  1.90video/s]

  [OK] '7 Jenama Phone Yang Stop Jual Phone!'  ->  294 comments  (total so far: 3,532)

Videos:   7%|▋         | 90/1248 [00:43<15:58,  1.21video/s]

  [OK] 'Tak Sangka iPhone Akan Jadi Android Juga Akhirnya...'  ->  63 comments  (total so far: 3,595)

Videos:   7%|▋         | 91/1248 [00:43<13:52,  1.39video/s]

  [OK] 'Dah jadi bapak-bapak ni baru dapat merasa 😂'  ->  6 comments  (total so far: 3,601)

Videos:   7%|▋         | 92/1248 [00:44<12:00,  1.60video/s]

  [OK] 'First Time Beli RC Monster Truck Yang POWER + Liar! 🔥'  ->  62 comments  (total so far: 3,663)

Videos:   7%|▋         | 93/1248 [00:44<11:49,  1.63video/s]

  [OK] 'Selamat Tinggal ASUS ROG Phone 2026 😭'  ->  74 comments  (total so far: 3,737)

Videos:   8%|▊         | 94/1248 [00:45<11:02,  1.74video/s]

  [OK] 'Gajet MENARIK Yang BEST Untuk Guna Tahun 2026! – EP1'  ->  23 comments  (total so far: 3,760)

Videos:   8%|▊         | 95/1248 [00:45<10:04,  1.91video/s]

  [OK] 'Foldable fon baru ni lebih kebal! 😱'  ->  4 comments  (total so far: 3,764)

Videos:   8%|▊         | 96/1248 [00:46<09:18,  2.06video/s]

  [OK] 'Unboxing Studio Baru FUZZ 2026! 🔥'  ->  19 comments  (total so far: 3,783)

Videos:   8%|▊         | 97/1248 [00:46<08:57,  2.14video/s]

  [OK] 'Bukti Fon OPPO Makin Bagus! – OPPO Reno 15 5G'  ->  22 comments  (total so far: 3,805)

Videos:   8%|▊         | 98/1248 [00:47<08:42,  2.20video/s]

  [OK] 'Jajan GR Corolla Aku Beli Kat Tokyo Auto Salon Japan 2026 🔥'  ->  64 comments  (total so far: 3,869)

Videos:   8%|▊         | 99/1248 [00:47<09:11,  2.08video/s]

  [OK] 'Video iPhone 17 Pro Max tak cukup power? 🤔'  ->  5 comments  (total so far: 3,874)

Videos:   8%|▊         | 100/1248 [00:47<08:37,  2.22video/s]

  [OK] 'Apple pun kalah dengan Google? 😰'  ->  27 comments  (total so far: 3,901)

Videos:   8%|▊         | 101/1248 [00:48<08:39,  2.21video/s]

  [OK] 'REDMI Note 15 Pro+ 5G : Harga Mampu Milik Tapi Lebih Lasak!'  ->  33 comments  (total so far: 3,934)

Videos:   8%|▊         | 102/1248 [00:48<08:45,  2.18video/s]

  [OK] 'Xiaomi pun ada Smart Glasses 😎'  ->  9 comments  (total so far: 3,943)

Videos:   8%|▊         | 103/1248 [00:49<08:25,  2.27video/s]

  [OK] 'HUAWEI Mate X7 Buat Aku Lebih YAKIN Guna Foldable Phone!'  ->  17 comments  (total so far: 3,960)

Videos:   8%|▊         | 104/1248 [00:49<08:15,  2.31video/s]

  [OK] 'Jumpa GR Corolla / GR Yaris Yang RARE Kat Tokyo Auto Salon Japan '  ->  23 comments  (total so far: 3,983)

Videos:   8%|▊         | 105/1248 [00:50<08:11,  2.32video/s]

  [OK] 'Sebab Samsung S25 Ultra Jadi Phone Terbaik 2025!'  ->  72 comments  (total so far: 4,055)

Videos:   8%|▊         | 106/1248 [00:50<08:13,  2.31video/s]

  [OK] 'First Mods Toyota GR Corolla Habis RM10,000! 🔥'  ->  94 comments  (total so far: 4,149)

Videos:   9%|▊         | 107/1248 [00:51<08:48,  2.16video/s]

  [OK] 'Aku Beli Kereta JDM Paling Rare di Malaysia!'  ->  156 comments  (total so far: 4,305)

Videos:   9%|▊         | 108/1248 [00:52<11:45,  1.62video/s]

  [OK] 'Tablet Baru HUAWEI Yang Dah Rasa Macam Laptop! – MatePad 12X 2026'  ->  26 comments  (total so far: 4,331)

Videos:   9%|▊         | 109/1248 [00:52<10:37,  1.79video/s]

  [OK] 'Smartphone Terbaik 2025 Pilihan FUZZ 🔥'  ->  94 comments  (total so far: 4,425)

Videos:   9%|▉         | 110/1248 [00:53<10:14,  1.85video/s]

  [OK] 'Pasang Benda Penting Kat Proton Saga MC3 2026!'  ->  50 comments  (total so far: 4,475)

Videos:   9%|▉         | 111/1248 [00:53<10:00,  1.89video/s]

  [OK] 'Ini Sebab Ramai Beli Google Pixel 10 Pro di Malaysia!'  ->  72 comments  (total so far: 4,547)

Videos:   9%|▉         | 112/1248 [00:53<09:42,  1.95video/s]

  [OK] 'Lenjan Proton Saga MC3 2026 Naik Genting! Tak Sangka....'  ->  285 comments  (total so far: 4,832)

Videos:   9%|▉         | 113/1248 [00:55<15:07,  1.25video/s]

  [OK] 'PUNCA Sebenar Masalah Proton Saga MC3 2026!'  ->  174 comments  (total so far: 5,006)

Videos:   9%|▉         | 114/1248 [00:56<15:46,  1.20video/s]

  [OK] 'Isu pasal kereta Proton Saga MC3'  ->  73 comments  (total so far: 5,079)

Videos:   9%|▉         | 115/1248 [00:56<13:29,  1.40video/s]

  [OK] 'Masalah Sebenar Proton Saga MC3 2026 Aku!'  ->  217 comments  (total so far: 5,296)

Videos:   9%|▉         | 116/1248 [00:58<17:29,  1.08video/s]

  [OK] 'Seram betul drive Proton Saga MC3 2026 😰'  ->  312 comments  (total so far: 5,608)

Videos:   9%|▉         | 117/1248 [01:00<23:13,  1.23s/video]

  [OK] 'First Time Beli Proton Saga MC3 Harga RM50K! – Test Semua Benda B'  ->  273 comments  (total so far: 5,881)

Videos:   9%|▉         | 118/1248 [01:01<24:41,  1.31s/video]

  [OK] 'Rupanya tak mahal pun guna Tesla ni 😄'  ->  11 comments  (total so far: 5,892)

Videos:  10%|▉         | 119/1248 [01:02<19:38,  1.04s/video]

  [OK] 'Dah boleh balas WhatsApp dekat Apple Watch 😍'  ->  8 comments  (total so far: 5,900)

Videos:  10%|▉         | 120/1248 [01:02<16:06,  1.17video/s]

  [OK] 'Kos Sebenar Guna Kereta EV di Malaysia Ramai Tak Tahu!'  ->  42 comments  (total so far: 5,942)

Videos:  10%|▉         | 121/1248 [01:02<13:44,  1.37video/s]

  [OK] 'Tablet pertama POCO dengan harga mampu miliki! – POCO Pad M1 😍'  ->  11 comments  (total so far: 5,953)

Videos:  10%|▉         | 122/1248 [01:03<11:58,  1.57video/s]

  [OK] 'Semua Phone Baru Makin Murah Sale 12.12 🔥'  ->  42 comments  (total so far: 5,995)

Videos:  10%|▉         | 123/1248 [01:03<10:52,  1.72video/s]

  [OK] 'Score AnTuTu paling tinggi maksudnya fon paling power la kan? 🫢'  ->  31 comments  (total so far: 6,026)

Videos:  10%|▉         | 124/1248 [01:04<10:06,  1.85video/s]

  [OK] 'Sebab Aku Jual Yamaha MT09 V4 (2025) + Review Lepas Hampir Setahu'  ->  129 comments  (total so far: 6,155)

Videos:  10%|█         | 125/1248 [01:05<12:49,  1.46video/s]

  [OK] 'Video iPhone 17 Pro Lebih CANTIK Guna Ni! – DJI Osmo Mobile 8'  ->  8 comments  (total so far: 6,163)

Videos:  10%|█         | 126/1248 [01:05<11:17,  1.66video/s]

  [OK] 'iQOO 15 : Pencabar Hebat POCO F8 Ultra di Malaysia!'  ->  38 comments  (total so far: 6,201)

Videos:  10%|█         | 127/1248 [01:06<10:03,  1.86video/s]

  [OK] 'Sebab Aku CANCEL Beli Perodua QV-E! – Realiti Sewa Bateri EV 🔥'  ->  608 comments  (total so far: 6,809)

Videos:  10%|█         | 128/1248 [01:09<28:12,  1.51s/video]

  [OK] 'Ini akan jadi kalau tak bayar sewa bater Perodua QV-E ⚡️'  ->  168 comments  (total so far: 6,977)

Videos:  10%|█         | 129/1248 [01:10<25:35,  1.37s/video]

  [OK] 'POCO F8 Ultra : Flagship Yang LENGKAP Siap Subwoofer Berharga RM2'  ->  64 comments  (total so far: 7,041)

Videos:  10%|█         | 130/1248 [01:11<20:21,  1.09s/video]

  [OK] 'Benda best & tak best dengan Perodua QV-E ⚡️'  ->  44 comments  (total so far: 7,085)

Videos:  10%|█         | 131/1248 [01:11<16:49,  1.11video/s]

  [OK] 'Beli Perodua QV-E Harga RM80,000 + Test Semua Benda Baru! 🔥'  ->  92 comments  (total so far: 7,177)

Videos:  11%|█         | 132/1248 [01:12<14:25,  1.29video/s]

  [OK] 'Android dah boleh Quick Share dengan iPhone! 😍'  ->  8 comments  (total so far: 7,185)

Videos:  11%|█         | 133/1248 [01:12<12:18,  1.51video/s]

  [OK] 'Apple Patut Takut Dengan HONOR Magic 8 Pro!'  ->  47 comments  (total so far: 7,232)

Videos:  11%|█         | 134/1248 [01:13<11:12,  1.66video/s]

  [OK] 'POCO F8 Pro terlalu murah untuk flagship! 😍'  ->  29 comments  (total so far: 7,261)

Videos:  11%|█         | 135/1248 [01:13<10:12,  1.82video/s]

  [OK] 'POCO F8 Pro : Flagship Killer Sebenar Dah Sampai Malaysia Harga R'  ->  65 comments  (total so far: 7,326)

Videos:  11%|█         | 136/1248 [01:14<09:39,  1.92video/s]

  [OK] 'Kereta Paling Mahal Pernah Aku Beli 🔥'  ->  44 comments  (total so far: 7,370)

Videos:  11%|█         | 137/1248 [01:14<09:17,  1.99video/s]

  [OK] 'Nothing phone paling murah kat Malaysia! Phone 3a Lite 🔥'  ->  8 comments  (total so far: 7,378)

Videos:  11%|█         | 138/1248 [01:14<08:42,  2.12video/s]

  [OK] 'Android boleh Quick Share dengan iPhone! 😍'  ->  10 comments  (total so far: 7,388)

Videos:  11%|█         | 139/1248 [01:15<08:24,  2.20video/s]

  [OK] 'Oakley Meta Vanguard Review : Boleh Rakam 3K Video + Bateri Tahan'  ->  9 comments  (total so far: 7,397)

Videos:  11%|█         | 140/1248 [01:15<08:07,  2.27video/s]

  [OK] 'Terlebih power Red Magic 11 Pro ni siap ada Liquid Cooling System'  ->  7 comments  (total so far: 7,404)

Videos:  11%|█▏        | 141/1248 [01:16<07:59,  2.31video/s]

  [OK] 'Bukti Kamera HONOR Magic8 Pro Bukan Biasa-Biasa!'  ->  52 comments  (total so far: 7,456)

Videos:  11%|█▏        | 142/1248 [01:16<08:08,  2.26video/s]

  [OK] 'Red Magic 11 Pro : Gaming Phone Paling POWER di Malaysia 🔥'  ->  44 comments  (total so far: 7,500)

Videos:  11%|█▏        | 143/1248 [01:17<07:58,  2.31video/s]

  [OK] 'OnePlus 15 Bukan Lagi OnePlus Kita Kenal!'  ->  33 comments  (total so far: 7,533)

Videos:  12%|█▏        | 144/1248 [01:17<07:57,  2.31video/s]

  [OK] 'Benda Penting Pasal iPhone 18 Pro Fold / Air 2'  ->  32 comments  (total so far: 7,565)

Videos:  12%|█▏        | 145/1248 [01:17<07:52,  2.33video/s]

  [OK] 'Oakley Meta Vanguard baru ni lagi best 😍'  ->  7 comments  (total so far: 7,572)

Videos:  12%|█▏        | 146/1248 [01:18<07:40,  2.39video/s]

  [OK] 'VIVO X300 Pro Review : Ini Bukti Kamera Fon Makin Power!'  ->  41 comments  (total so far: 7,613)

Videos:  12%|█▏        | 147/1248 [01:18<07:47,  2.35video/s]

  [OK] 'realme GT8 Pro Dah Sampai Malaysia! Lebih Power + Berbeza...'  ->  24 comments  (total so far: 7,637)

Videos:  12%|█▏        | 148/1248 [01:19<07:56,  2.31video/s]

  [OK] 'Kereta Tesla aku kena langgar 😢'  ->  78 comments  (total so far: 7,715)

Videos:  12%|█▏        | 149/1248 [01:19<08:25,  2.17video/s]

  [OK] 'Semua Phone SEDAP Makin Murah Sale 11.11 🔥'  ->  68 comments  (total so far: 7,783)

Videos:  12%|█▏        | 150/1248 [01:20<09:01,  2.03video/s]

  [OK] 'Nubia Z80 Ultra dah sampai Malaysia harga RM3399 🔥'  ->  13 comments  (total so far: 7,796)

Videos:  12%|█▏        | 151/1248 [01:20<08:32,  2.14video/s]

  [OK] 'Nubia Z80 Ultra : Fon Flagship Termurah Guna Snapdragon 8 Elite G'  ->  36 comments  (total so far: 7,832)

Videos:  12%|█▏        | 152/1248 [01:21<08:33,  2.14video/s]

  [OK] 'Update Penting iOS 26.1 Untuk iPhone 17 Pro! – Banyak Fungsi Baru'  ->  34 comments  (total so far: 7,866)

Videos:  12%|█▏        | 153/1248 [01:21<08:37,  2.12video/s]

  [OK] 'VIVO X300 Pro : Inilah Flagship Camera Phone Sebenar! 🔥 (Photogra'  ->  76 comments  (total so far: 7,942)

Videos:  12%|█▏        | 154/1248 [01:22<08:41,  2.10video/s]

  [OK] 'Baik beli Insta360 X4 Air atau X5? Sebab dua-dua pun power jugak '  ->  2 comments  (total so far: 7,944)

Videos:  12%|█▏        | 155/1248 [01:22<08:11,  2.22video/s]

  [OK] 'Aku Order ROBOT Manusia Harga RM83K! – 1X NEO Home Robot'  ->  38 comments  (total so far: 7,982)

Videos:  12%|█▎        | 156/1248 [01:22<08:14,  2.21video/s]

  [OK] 'Fon OPPO boleh AirDrop dengan iPhone 17 Pro?! 😱'  ->  15 comments  (total so far: 7,997)

Videos:  13%|█▎        | 157/1248 [01:23<08:14,  2.21video/s]

  [OK] 'OPPO Find X9 Pro : Rasa Macam iPhone 17 Pro, Tapi Kamera Lagi POW'  ->  56 comments  (total so far: 8,053)

Videos:  13%|█▎        | 158/1248 [01:23<08:08,  2.23video/s]

  [OK] 'Insta360 X4 Air ni kecik je tapi power macam X5 🔥'  ->  10 comments  (total so far: 8,063)

Videos:  13%|█▎        | 159/1248 [01:24<07:49,  2.32video/s]

  [OK] 'Selamat Tinggal... 😭'  ->  74 comments  (total so far: 8,137)

Videos:  13%|█▎        | 160/1248 [01:24<08:06,  2.24video/s]

  [OK] 'iPhone 15 Pro Max (2025) Review : Lepas 2 Tahun Masih Bagus?! 🤔'  ->  78 comments  (total so far: 8,215)

Videos:  13%|█▎        | 161/1248 [01:25<08:02,  2.25video/s]

  [OK] 'iPhone 17 Pro Max Review : Akhirnya Lengkap! Tapi...'  ->  42 comments  (total so far: 8,257)

Videos:  13%|█▎        | 162/1248 [01:25<08:18,  2.18video/s]

  [OK] 'Guna Air Purifier Ni Kat Rumah, Confirmed Udara Bersih!'  ->  9 comments  (total so far: 8,266)

Videos:  13%|█▎        | 163/1248 [01:26<07:57,  2.27video/s]

  [OK] 'Problem baru iPhone 17 Pro! 🥵'  ->  45 comments  (total so far: 8,311)

Videos:  13%|█▎        | 164/1248 [01:26<08:25,  2.15video/s]

  [OK] 'Baru Sebulan, iPhone 17 Pro Max Dah Ada MASALAH! 😰'  ->  196 comments  (total so far: 8,507)

Videos:  13%|█▎        | 165/1248 [01:27<11:21,  1.59video/s]

  [OK] 'Fungsi MENARIK iPhone 17 Pro Tak Ramai Tahu! 🔥'  ->  35 comments  (total so far: 8,542)

Videos:  13%|█▎        | 166/1248 [01:27<10:03,  1.79video/s]

  [OK] 'Tips battery iPhone tahan lebih lama! 😋'  ->  10 comments  (total so far: 8,552)

Videos:  13%|█▎        | 167/1248 [01:28<09:10,  1.96video/s]

  [OK] 'Aku Setup Gaming RM10,000 Dengan Haier Smart TV 85" M80 Series!'  ->  11 comments  (total so far: 8,563)

Videos:  13%|█▎        | 168/1248 [01:28<08:35,  2.10video/s]

  [OK] 'Google Pixel PALING MAHAL Di Malaysia! – Pixel 10 Pro Fold'  ->  21 comments  (total so far: 8,584)

Videos:  14%|█▎        | 169/1248 [01:29<08:10,  2.20video/s]

  [OK] '5 Phone Flagship RM3000 Makin Murah Sale 10.10!'  ->  38 comments  (total so far: 8,622)

Videos:  14%|█▎        | 170/1248 [01:29<08:15,  2.17video/s]

  [OK] 'CMF Headphone Pro & Watch 3 Pro dah sampai Malaysia! 🥰'  ->  5 comments  (total so far: 8,627)

Videos:  14%|█▎        | 171/1248 [01:30<07:59,  2.25video/s]

  [OK] '5 Phone Flagship POWER Masuk Malaysia! – Xiaomi 17 Pro Pun Ada 🔥'  ->  98 comments  (total so far: 8,725)

Videos:  14%|█▍        | 172/1248 [01:30<08:06,  2.21video/s]

  [OK] 'Smartwatch Dengan Bateri Tahan 21 Hari! – HUAWEI Watch GT 6 Serie'  ->  8 comments  (total so far: 8,733)

Videos:  14%|█▍        | 173/1248 [01:30<07:38,  2.34video/s]

  [OK] 'Masalah dengan iPhone 17 Pro Max! 🔥'  ->  10 comments  (total so far: 8,743)

Videos:  14%|█▍        | 174/1248 [01:31<08:18,  2.15video/s]

  [OK] '5 Sebab JANGAN BELI iPhone Air'  ->  78 comments  (total so far: 8,821)

Videos:  14%|█▍        | 175/1248 [01:31<08:21,  2.14video/s]

  [OK] 'Beli iPhone 17 Pro Max Atau 16 Pro Max? – Perbezaan & Persamaan!'  ->  50 comments  (total so far: 8,871)

Videos:  14%|█▍        | 176/1248 [01:32<08:39,  2.06video/s]

  [OK] 'Bateri boleh tahan sampai 21 hari! – HUAWEI Watch GT 6 Series 😱'  ->  3 comments  (total so far: 8,874)

Videos:  14%|█▍        | 177/1248 [01:32<08:16,  2.16video/s]

  [OK] 'Xiaomi 15T Pro kali ni lagi power kamera dia! 🔥'  ->  19 comments  (total so far: 8,893)

Videos:  14%|█▍        | 178/1248 [01:33<08:14,  2.16video/s]

  [OK] 'Samsung Tab S11 Ultra Dah Sampai! – Lagi Nipis Dari iPhone Air 🔥'  ->  24 comments  (total so far: 8,917)

Videos:  14%|█▍        | 179/1248 [01:33<08:06,  2.20video/s]

  [OK] 'Apple downgrade iPhone 17 Pro Max?! 😱'  ->  42 comments  (total so far: 8,959)

Videos:  14%|█▍        | 180/1248 [01:34<08:01,  2.22video/s]

  [OK] 'VLOG New Zealand : Explore Keindahan Lake Tekapo, Queenstown & Mi'  ->  57 comments  (total so far: 9,016)

Videos:  15%|█▍        | 181/1248 [01:34<08:12,  2.17video/s]

  [OK] 'Test video ProRes RAW iPhone 17 Pro Max 🔥'  ->  9 comments  (total so far: 9,025)

Videos:  15%|█▍        | 182/1248 [01:35<07:53,  2.25video/s]

  [OK] 'Laptop Paling SUSAH ROSAK Terbaru ASUS ExpertBook PM3!'  ->  15 comments  (total so far: 9,040)

Videos:  15%|█▍        | 183/1248 [01:35<07:56,  2.24video/s]

  [OK] 'Xiaomi 15T Pro : Flagship Mampu Milik Dengan Camera Lagi POWER!'  ->  68 comments  (total so far: 9,108)

Videos:  15%|█▍        | 184/1248 [01:36<08:11,  2.16video/s]

  [OK] 'HONOR X9d : Phone Susah Pecah Dengan 8300mAh Battery!'  ->  81 comments  (total so far: 9,189)

Videos:  15%|█▍        | 185/1248 [01:36<08:12,  2.16video/s]

  [OK] 'Yamaha MT09 V4 lepas 6 bulan 🥰'  ->  69 comments  (total so far: 9,258)

Videos:  15%|█▍        | 186/1248 [01:36<08:21,  2.12video/s]

  [OK] 'Life hacks menarik dengan phone Samsung! ✨'  ->  13 comments  (total so far: 9,271)

Videos:  15%|█▍        | 187/1248 [01:37<08:01,  2.20video/s]

  [OK] '3 benda wajib tahu pasal iPhone Air 🔥'  ->  33 comments  (total so far: 9,304)

Videos:  15%|█▌        | 188/1248 [01:37<08:11,  2.16video/s]

  [OK] 'iPhone Air Review : Menyesal Beli? Lenjan Sampai Overheat! 🔥'  ->  101 comments  (total so far: 9,405)

Videos:  15%|█▌        | 189/1248 [01:38<10:11,  1.73video/s]

  [OK] 'Phone FUZZ tengah guna sekarang 😋'  ->  62 comments  (total so far: 9,467)

Videos:  15%|█▌        | 190/1248 [01:39<09:34,  1.84video/s]

  [OK] 'iPhone Air terlalu nipis! 🍃'  ->  16 comments  (total so far: 9,483)

Videos:  15%|█▌        | 191/1248 [01:39<09:00,  1.96video/s]

  [OK] 'All new iPhone 17 Pro Max 🔥'  ->  17 comments  (total so far: 9,500)

Videos:  15%|█▌        | 192/1248 [01:40<08:29,  2.07video/s]

  [OK] 'Beratur pickup iPhone 17 kat Apple Store TRX! 😱'  ->  92 comments  (total so far: 9,592)

Videos:  15%|█▌        | 193/1248 [01:40<08:47,  2.00video/s]

  [OK] 'Unboxing iPhone Air : Terlalu Ringan, Tapi Bukan Untuk Semua!'  ->  69 comments  (total so far: 9,661)

Videos:  16%|█▌        | 194/1248 [01:41<08:34,  2.05video/s]

  [OK] 'Unboxing iPhone 17 Pro Max : Semua Yang Baru!'  ->  185 comments  (total so far: 9,846)

Videos:  16%|█▌        | 195/1248 [01:42<11:53,  1.48video/s]

  [OK] 'AI Dari iPhone 17 Pun KALAH Dengan realme 15 Pro! 🔥'  ->  54 comments  (total so far: 9,900)

Videos:  16%|█▌        | 196/1248 [01:42<10:42,  1.64video/s]

  [OK] 'Rahsia phone Samsung yang tak ramai tahu! 😱'  ->  4 comments  (total so far: 9,904)

Videos:  16%|█▌        | 197/1248 [01:42<09:34,  1.83video/s]

  [OK] 'Laptop tahan lasak terbaru ASUS ExpertBook Series! 🔥'  ->  5 comments  (total so far: 9,909)

Videos:  16%|█▌        | 198/1248 [01:43<08:39,  2.02video/s]

  [OK] 'Xiaomi 17 Pro Tiru iPhone 17 Pro?! – Nampak Sama, Tapi Tak Serupa'  ->  112 comments  (total so far: 10,021)

Videos:  16%|█▌        | 199/1248 [01:44<11:25,  1.53video/s]

  [OK] 'Untung betul pengguna HUAWEI sekarang 😍'  ->  8 comments  (total so far: 10,029)

Videos:  16%|█▌        | 200/1248 [01:44<10:14,  1.71video/s]

  [OK] 'Smartphone korang boleh buat macam ni? 😙'  ->  14 comments  (total so far: 10,043)

Videos:  16%|█▌        | 201/1248 [01:45<09:17,  1.88video/s]

  [OK] 'iPhone Air : Skip atau Beli? Sesuai Untuk Siapa?'  ->  47 comments  (total so far: 10,090)

Videos:  16%|█▌        | 202/1248 [01:45<09:00,  1.94video/s]

  [OK] 'Power juga HUAWEI Pura 80 terbaru ni! 😍'  ->  10 comments  (total so far: 10,100)

Videos:  16%|█▋        | 203/1248 [01:46<08:38,  2.01video/s]

  [OK] 'iPhone Air terlalu mahal untuk basic iPhone? 🤔'  ->  38 comments  (total so far: 10,138)

Videos:  16%|█▋        | 204/1248 [01:46<08:31,  2.04video/s]

  [OK] 'iPhone 17 Pro / Air : Semua Benda Baru Wajib Tahu!'  ->  171 comments  (total so far: 10,309)

Videos:  16%|█▋        | 205/1248 [01:47<11:37,  1.49video/s]

  [OK] 'Cukup ke atau tak cukup lagi? 😅'  ->  12 comments  (total so far: 10,321)

Videos:  17%|█▋        | 206/1248 [01:48<10:23,  1.67video/s]

  [OK] 'Ini Dia Tablet Paling LAKU KERAS di Malaysia!'  ->  38 comments  (total so far: 10,359)

Videos:  17%|█▋        | 207/1248 [01:48<09:25,  1.84video/s]

  [OK] 'Galaxy S25 FE : Flagship Mampu Milik Dari Samsung'  ->  33 comments  (total so far: 10,392)

Videos:  17%|█▋        | 208/1248 [01:49<08:53,  1.95video/s]

  [OK] 'Phone HUAWEI Dah Boleh Guna Google Apps?! 😱'  ->  30 comments  (total so far: 10,422)

Videos:  17%|█▋        | 209/1248 [01:49<08:30,  2.04video/s]

  [OK] 'DJI Mic 3 terbaru lagi kecik tapi power! 😍'  ->  1 comments  (total so far: 10,423)

Videos:  17%|█▋        | 210/1248 [01:49<08:02,  2.15video/s]

  [OK] '10 Phone PALING MAHAL Dunia & Malaysia! 😱'  ->  45 comments  (total so far: 10,468)

Videos:  17%|█▋        | 211/1248 [01:50<07:59,  2.16video/s]

  [OK] 'Google Pixel 10 Review : Bukan Flagship, iPhone Versi Android?'  ->  56 comments  (total so far: 10,524)

Videos:  17%|█▋        | 212/1248 [01:50<08:20,  2.07video/s]

  [OK] 'Apple Event dah confirmed iPhone 17 Series baru! 😍'  ->  20 comments  (total so far: 10,544)

Videos:  17%|█▋        | 213/1248 [01:51<08:14,  2.09video/s]

  [OK] 'VIVO V60 : Fon Mid-Range Yang Lengkap Bawah RM2000 di Malaysia!'  ->  50 comments  (total so far: 10,594)

Videos:  17%|█▋        | 214/1248 [01:51<08:20,  2.06video/s]

  [OK] 'Kamera kecik serba boleh! 🔥 #Insta360GOUltra'  ->  3 comments  (total so far: 10,597)

Videos:  17%|█▋        | 215/1248 [01:52<07:52,  2.19video/s]

  [OK] 'HONOR MagicPad 3 : Tablet Paling Best Bawah RM3000!'  ->  28 comments  (total so far: 10,625)

Videos:  17%|█▋        | 216/1248 [01:53<10:54,  1.58video/s]

  [OK] 'Punca sebenar jari tangan bengkok! 😱'  ->  30 comments  (total so far: 10,655)

Videos:  17%|█▋        | 217/1248 [01:53<09:58,  1.72video/s]

  [OK] 'Insta360 GO ULTRA Review : Kamera Kecik Paling SERBA BOLEH!'  ->  15 comments  (total so far: 10,670)

Videos:  17%|█▋        | 218/1248 [01:54<09:07,  1.88video/s]

  [OK] 'Aku rasa bukan phone ni 🧐'  ->  16 comments  (total so far: 10,686)

Videos:  18%|█▊        | 219/1248 [01:54<08:27,  2.03video/s]

  [OK] 'Google Pixel 10 Pro / Fold Dah Sampai Malaysia Harga RM8000!'  ->  38 comments  (total so far: 10,724)

Videos:  18%|█▊        | 220/1248 [01:54<08:14,  2.08video/s]

  [OK] 'Skrin tablet paling sedap 2025 😍'  ->  12 comments  (total so far: 10,736)

Videos:  18%|█▊        | 221/1248 [01:55<07:40,  2.23video/s]

  [OK] 'Teknologi Phone Yang GAGAL + PUPUS!'  ->  323 comments  (total so far: 11,059)

Videos:  18%|█▊        | 222/1248 [01:57<15:54,  1.07video/s]

  [OK] 'iPhone 17 Pro Max dah keluar?! 😱'  ->  36 comments  (total so far: 11,095)

Videos:  18%|█▊        | 223/1248 [01:57<13:50,  1.23video/s]

  [OK] 'POV sehari bersama FUZZ 🥰'  ->  7 comments  (total so far: 11,102)

Videos:  18%|█▊        | 224/1248 [01:58<11:51,  1.44video/s]

  [OK] '200MP Camera Battle : Samsung Galaxy Z Fold7 vs S25 Ultra 🔥'  ->  13 comments  (total so far: 11,115)

Videos:  18%|█▊        | 225/1248 [01:58<10:23,  1.64video/s]

  [OK] 'POV long distance drive EV Tesla ⚡️'  ->  12 comments  (total so far: 11,127)

Videos:  18%|█▊        | 226/1248 [01:59<09:20,  1.82video/s]

  [OK] '5 Benda TAK BEST Dengan Tesla Model 3 2025!'  ->  37 comments  (total so far: 11,164)

Videos:  18%|█▊        | 227/1248 [01:59<08:50,  1.92video/s]

  [OK] 'Samsung Galaxy Watch 8 Classic pun dah cukup power! 🔥'  ->  6 comments  (total so far: 11,170)

Videos:  18%|█▊        | 228/1248 [02:00<08:19,  2.04video/s]

  [OK] '9 Phone SEDAP Makin MURAH Sale 8.8 di Malaysia!'  ->  56 comments  (total so far: 11,226)

Videos:  18%|█▊        | 229/1248 [02:00<08:10,  2.08video/s]

  [OK] 'Visit Google Malaysia punya office kat KL 🥰'  ->  11 comments  (total so far: 11,237)

Videos:  18%|█▊        | 230/1248 [02:00<07:59,  2.12video/s]

  [OK] 'Masalah Dengan Foldable Phone! Drop Test HONOR Magic V5 🔥'  ->  37 comments  (total so far: 11,274)

Videos:  19%|█▊        | 231/1248 [02:01<07:58,  2.12video/s]

  [OK] 'iOS 26 Public Beta dah boleh update!'  ->  5 comments  (total so far: 11,279)

Videos:  19%|█▊        | 232/1248 [02:01<07:42,  2.20video/s]

  [OK] 'iPhone 17 Air dah confirmed?! 😱'  ->  55 comments  (total so far: 11,334)

Videos:  19%|█▊        | 233/1248 [02:02<08:12,  2.06video/s]

  [OK] 'Kamera HUAWEI Pura 80 Pro memang next level! 😱'  ->  21 comments  (total so far: 11,355)

Videos:  19%|█▉        | 234/1248 [02:02<07:50,  2.15video/s]

  [OK] 'Tecno Pova 7 Ultra : Gaming Phone Bajet RM1399 Paling Berbaloi?!'  ->  38 comments  (total so far: 11,393)

Videos:  19%|█▉        | 235/1248 [02:03<07:59,  2.11video/s]

  [OK] 'DJI OSMO 360 Review : Action Camera 360 Terbaik 2025 Berharga RM1'  ->  57 comments  (total so far: 11,450)

Videos:  19%|█▉        | 236/1248 [02:03<07:39,  2.20video/s]

  [OK] 'Foldable Pertama VIVO Malaysia Dah Sampai! – VIVO X Fold 5 🔥'  ->  32 comments  (total so far: 11,482)

Videos:  19%|█▉        | 237/1248 [02:04<07:38,  2.20video/s]

  [OK] 'Kos first service Yamaha MT09 V4 2025 🤑'  ->  23 comments  (total so far: 11,505)

Videos:  19%|█▉        | 238/1248 [02:04<07:39,  2.20video/s]

  [OK] 'Tablet Gaming Paling POWER Guna Snapdragon 8 Elite! – Red Magic A'  ->  93 comments  (total so far: 11,598)

Videos:  19%|█▉        | 239/1248 [02:05<07:58,  2.11video/s]

  [OK] 'HUAWEI Pura 80 Ultra Dah Sampai Malaysia Harga RM6599! 🔥'  ->  47 comments  (total so far: 11,645)

Videos:  19%|█▉        | 240/1248 [02:05<07:50,  2.14video/s]

  [OK] 'VLOG New York : 24 Jam Flight! Rasa Macam Dalam Movie 🥰'  ->  79 comments  (total so far: 11,724)

Videos:  19%|█▉        | 241/1248 [02:06<07:52,  2.13video/s]

  [OK] 'Masalah dengan EV charger 🥵'  ->  223 comments  (total so far: 11,947)

Videos:  19%|█▉        | 242/1248 [02:07<14:01,  1.20video/s]

  [OK] 'HONOR Magic V5 Review : Foldable Termurah di Malaysia Berharga RM'  ->  34 comments  (total so far: 11,981)

Videos:  19%|█▉        | 243/1248 [02:08<11:58,  1.40video/s]

  [OK] 'Perubahan Besar iPhone 17 Air / 17 Pro Harga Cecah RM9000?!'  ->  19 comments  (total so far: 12,000)

Videos:  20%|█▉        | 244/1248 [02:08<08:49,  1.90video/s]

Reached 12,000 comment cap — stopping early.

Collection complete.
  Total comments collected : 12,000
  Videos skipped           : 1

## 9. Inspect the Raw Dataset

Before saving, we do a quick sanity check:
- Confirm the schema looks correct.
- Check for obvious issues such as blank comment text or duplicate comment IDs.
- Review the per-video comment distribution.

In [9]:
df_raw = pd.DataFrame(all_records)

print("=== Shape ===")
print(f"  Rows    : {df_raw.shape[0]:,}")
print(f"  Columns : {df_raw.shape[1]}")

print("\n=== Column types ===")
print(df_raw.dtypes)

print("\n=== Missing values ===")
print(df_raw.isnull().sum())

print("\n=== Duplicate comment IDs ===")
dupes = df_raw.duplicated(subset="comment_id").sum()
print(f"  {dupes} duplicate(s) found")

print("\n=== Sample rows ===")
df_raw[["video_title", "author", "comment_text", "like_count", "published_at"]].head(5)

=== Shape ===
  Rows    : 12,000
  Columns : 10

=== Column types ===
video_id                str
video_title             str
video_published_at      str
comment_id              str
author                  str
comment_text            str
like_count            int64
reply_count           int64
published_at            str
updated_at              str
dtype: object

=== Missing values ===
video_id              0
video_title           0
video_published_at    0
comment_id            0
author                0
comment_text          0
like_count            0
reply_count           0
published_at          0
updated_at            0
dtype: int64

=== Duplicate comment IDs ===
  0 duplicate(s) found

=== Sample rows ===

,video_title,author,comment_text,like_count,published_at
0,Selamat Tinggal iPad... Dah Jumpa Tablet Lagi ...,@faizulirfan22,"For me, tablet/ipad tak boleh replace the lapt...",23,2026-06-18T17:56:46Z
1,Selamat Tinggal iPad... Dah Jumpa Tablet Lagi ...,@adzalanmdamin8154,tablet huawei da lama pintas ipad pun...4 tahu...,11,2026-06-19T05:47:30Z
2,Selamat Tinggal iPad... Dah Jumpa Tablet Lagi ...,@ayeemasrii,hopefully through update features je yg boleh ...,1,2026-06-18T20:05:41Z
3,Selamat Tinggal iPad... Dah Jumpa Tablet Lagi ...,@zamzuri13,"nak connectkan AI platform dengan OpenClaw tu,...",2,2026-06-18T14:03:34Z
4,Selamat Tinggal iPad... Dah Jumpa Tablet Lagi ...,@muhammadnazirulbakarudin7250,Kenapa susunan icon dia lebih banyak dari magi...,2,2026-06-19T02:12:49Z

In [10]:
# Per-video comment count distribution
video_stats = (
    df_raw.groupby("video_title")["comment_id"]
    .count()
    .rename("comment_count")
    .sort_values(ascending=False)
    .reset_index()
)

print(f"Videos with collected comments: {len(video_stats)}")
print()
print("Top 10 most-commented videos:")
print(video_stats.head(10).to_string(index=False))

print("\nComment count stats:")
print(video_stats["comment_count"].describe().to_string())

Videos with collected comments: 243

Top 10 most-commented videos:
                                                           video_title  comment_count
        Sebab Aku CANCEL Beli Perodua QV-E! – Realiti Sewa Bateri EV 🔥            608
                                   Teknologi Phone Yang GAGAL + PUPUS!            323
                              Seram betul drive Proton Saga MC3 2026 😰            312
                                  7 Jenama Phone Yang Stop Jual Phone!            294
              Lenjan Proton Saga MC3 2026 Naik Genting! Tak Sangka....            285
First Time Beli Proton Saga MC3 Harga RM50K! – Test Semua Benda Baru 🔥            273
                                           Masalah dengan EV charger 🥵            223
                             Masalah Sebenar Proton Saga MC3 2026 Aku!            217
                    Baru Sebulan, iPhone 17 Pro Max Dah Ada MASALAH! 😰            196
                         Unboxing iPhone 17 Pro Max : Semua Yang Baru!            185

Comment count stats:
count    243.000000
mean      49.382716
std       64.246665
min        1.000000
25%       14.500000
50%       33.000000
75%       60.500000
max      608.000000

## 10. Save Raw Data

We save the unmodified DataFrame to `data/raw_data/youtube_comments_raw.csv`.

- **UTF-8-sig** encoding is used so the file opens correctly in Excel (adds a BOM marker).
- The index is excluded (`index=False`) to keep the CSV clean.
- A **metadata JSON sidecar** is written alongside the CSV to document when and how the data was collected — useful for reproducibility.

In [11]:
# Save CSV
df_raw.to_csv(OUTPUT_FILE, index=False, encoding="utf-8-sig")
print(f"Raw CSV saved  -> {os.path.abspath(OUTPUT_FILE)}")
print(f"  Rows : {len(df_raw):,}")
print(f"  Size : {os.path.getsize(OUTPUT_FILE) / 1024:.1f} KB")

# Save collection metadata sidecar
metadata = {
    "collected_at"       : datetime.utcnow().isoformat() + "Z",
    "channel_title"      : CHANNEL_TITLE,
    "channel_id"         : CHANNEL_ID,
    "uploads_playlist"   : UPLOADS_PLAYLIST_ID,
    "total_channel_vids" : len(all_videos),
    "videos_targeted"    : len(target_videos),
    "videos_skipped"     : len(skipped),
    "total_comments"     : len(df_raw),
    "output_file"        : os.path.abspath(OUTPUT_FILE),
}

meta_file = OUTPUT_FILE.replace(".csv", "_metadata.json")
with open(meta_file, "w", encoding="utf-8") as fh:
    json.dump(metadata, fh, indent=2)

print(f"Metadata saved -> {os.path.abspath(meta_file)}")

Raw CSV saved  -> c:\UTM things\Year 3\SEM 2\HDPD\Project 2\data\raw_data\youtube_comments_raw.csv
  Rows : 12,000
  Size : 3102.7 KB
Metadata saved -> c:\UTM things\Year 3\SEM 2\HDPD\Project 2\data\raw_data\youtube_comments_raw_metadata.json

## 11. Collection Summary

The table below summarises what was collected in this run.

In [12]:
summary = pd.DataFrame([
    {"Metric": "Channel",                        "Value": CHANNEL_TITLE},
    {"Metric": "Total videos on channel",         "Value": str(len(all_videos))},
    {"Metric": "Videos targeted",                 "Value": str(len(target_videos))},
    {"Metric": "Videos with comments collected",  "Value": str(len(target_videos) - len(skipped))},
    {"Metric": "Videos skipped (no comments)",    "Value": str(len(skipped))},
    {"Metric": "Total comments collected",        "Value": f"{len(df_raw):,}"},
    {"Metric": "Unique videos in dataset",        "Value": str(df_raw['video_id'].nunique())},
    {"Metric": "Output file",                     "Value": OUTPUT_FILE},
])

summary.index = [""] * len(summary)
display(summary)

,Metric,Value
,Channel,FUZZ CHANNEL
,Total videos on channel,1248
,Videos targeted,1248
,Videos with comments collected,1247
,Videos skipped (no comments),1
,Total comments collected,"12,000"
,Unique videos in dataset,243
,Output file,c:\UTM things\Year 3\SEM 2\HDPD\Project 2\data...